// GENERATED by tools/modernhud_pack.py -- DO NOT EDIT.
// pack: basic  (Basic)
// source of truth: config/ModernHUD/Packs/basic/pack.json
// format 2, generator 3, framework 2
//
// Regenerate with:
//   python tools/modernhud_pack.py --generate config/ModernHUD/Packs/basic/pack.json
// Hand edits are lost. To hand-author instead, set the manifest's
// "authoring" to "manual" -- the generator then refuses to overwrite.

exec("ModernHUD/Framework.cs");

$ModernHUD::Enabled = true;
$ModernHUD::Pack = "Basic";
$ModernHUD::PackId = "basic";

// A part is ours unless the player selected another pack's module for its
// slot. ModernHUD is immediate-mode, so hiding retained controls cannot
// disable one of our parts -- the draw dispatch must yield the slot.
function ModernHUDPack::ownsSlot(%value)
{
   if(%value == "")
      return true;
   if(%value == "off")
      return false;
   return String::findSubStr(%value, "Basic::") == 0;
}

// Remove the retained containers these parts replace. Detaching (rather
// than only hiding) leaves exactly one movable identity per component and
// stops the old control from eating K-editor clicks.
function ModernHUDPack::detachRetained()
{
   ModernHUD::detachContainer("CTFHUD::Container");
   ModernHUD::detachContainer("GAmmo::Container");
   ModernHUD::detachContainer("GEnergy::Container");
   ModernHUD::detachContainer("GHealth::Container");
   ModernHUD::detachContainer("GSpeed::Container");
   ModernHUD::detachContainer("ItemHUD::Container");
   ModernHUD::detachContainer("LegendzFPSHUD::Container");
   ModernHUD::detachContainer("ToastyHUD::Container");
}

// The pack's own stock-HUD preferences (minimap shape/size, stock hud
// placement). Applied on load, as the legacy loader does for a legacy pack.
function ModernHUDPack::prefs()
{
   $pref::hudPositionsAmmoHUD::Container = "15 938||0.00885 0.933333 0";
   $pref::hudPositionsclock::Container = "899 16||0.510795 0.015534 0";
   $pref::hudPositionsCtfHUD::Container = "||";
   $pref::hudPositionsElephant::Container = "1719 927||0.987931 0.996774 0";
   $pref::hudPositionsEnemy_Hud = "17 661||0.009884 0.847436 0";
   $pref::hudPositionsFlagCheck::Container = "763 959||0.486624 0.904717 0";
   $pref::hudPositionsFlagPopup::Container = "606 67||0.507963 0.063931 0";
   $pref::hudPositionsGAmmo::Container = "||";
   $pref::hudPositionsGEnergy::Container = "||";
   $pref::hudPositionsGHealth::Container = "||";
   $pref::hudPositionsGSpeed::Container = "||";
   $pref::hudPositionsHitCG1_Hud = "930 510||0 0 0";
   $pref::hudPositionsHUDOverlay::Container = "18 8||0.011688 0.011429 0";
   $pref::hudPositionsItemHUD::Container = "||";
   $pref::hudPositionsLegendzFPSHUD::Container = "||";
   $pref::hudPositionsLiuKangCap::Container = "0 565||-1 0 0";
   $pref::hudPositionsRatingsHUD::Container = "1695 990||1 1 0";
   $pref::hudPositionsScorpionCap::Container = "362 626||0.217548 0.739079 0";
   $pref::hudPositionsToastyHUD::Container = "||";
   $pref::miniMapAlpha = "1";
   $pref::miniMapAutosize = "False";
   $pref::miniMapRotate = "True";
   $pref::miniMapSquare = "False";
   $pref::miniMapWidth = "300";
   $pref::miniMapZoom = "1.75";
}

function ModernHUDPack::stockHuds()
{
   // Visibility only -- placement rides the stock huds' own
   // $pref::hudPositions entries, which the engine re-anchors.
   //
   // ModernHUD::stock is Control::SetVisible with a player row in front
   // of it: the value here is this pack's DEFAULT, and the K panel's row
   // overrides it. Controls outside STOCK_PLAYER_ROWS keep the direct
   // call -- see the note on that list in this generator.
   Control::SetVisible(crosshairHud, true);
   ModernHUD::stock(clockHud, true);
   ModernHUD::stock(sensorHUD, false);
   ModernHUD::stock(compassHud, false);
   ModernHUD::stock(jetPackHud, true);
   ModernHUD::stock(healthHud, true);
   ModernHUD::stock(weaponHud, false);
   ModernHUD::stock(chatDisplayHud, true);
   ModernHUD::stock(Minimap, true);
   Control::SetVisible(reticleCompass, false);
}

ModernHUD::require("ModernHUD/Core/Data/Team.cs");
ModernHUD::require("ModernHUD/Core/Data/Timer.cs");

// ---- helpers carried from the legacy pack -------------------------
// A lifted body calls these; the converted pack does not execute the
// legacy module, so they have to come along or the call resolves to
// nothing and the part renders wrong without erroring.
//
// ★Prefixed with the pack id.★ Five packs define CTFHUD::Update; the
// console has one namespace and a definition outlives the pack that made
// it, so under the original names a leftover handler from a pack that is
// no longer loaded would call OUR body. The originals are recorded below
// each definition.
// from Modules/CTFHud/CTFHud.acs.cs  (originally CTFHUD::EnemyTeamValue)
function basic::CTFHUD::EnemyTeamValue(%team, %score1)
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
       %team = Team::Enemy();
   %loc = Team::Flag::Location(Team::Enemy());

   basic::FlagFlash(%team);

   switch ( %loc ) {
       case "home":
           %loc = "<f:small-black-stroke.pft:FFFFFFFF:000000ff:1,1>Home";
           %bmp = "Assets/Packs/basic/modules/ctfhud/flag-icon.png:ff0000ff";
           break;
       case "field":
           %loc = $FlagDropFont ~ Team::Flag::Timer(%team);
           %bmp = $FlagDropIcon1;
           break;
       default:
           %loc = String::escapeFormatting(Client::GetName(%loc));
           %bmp = "Assets/Packs/basic/modules/ctfhud/flag-icon.png:00d2ffff";
           break;
   }
   ModernHUD::markup(%x + 55, %y + 32, 445, "<f:font-nostroke.pft:006880ff:006880ff:1,1>" ~ %loc, 255);
   ModernHUD::markup(%x + 55, %y + 32, 445, "<f:font-stroke.pft:00cfff>" ~ %loc, 255);

   ModernHUD::markup(%x + 0, %y + 25, 500, "<b3,3:"~%bmp~">", 255);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally CTFHUD::FriendlyTeamValue)
function basic::CTFHUD::FriendlyTeamValue(%team, %score0)
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
       %team = Team::Friendly();
   %loc = Team::Flag::Location(Team::Friendly());

   basic::FlagFlash(%team);

   switch ( %loc ) {
       case "home":
           %loc = "<f:small-black-stroke.pft:FFFFFFFF:000000ff:1,1>Home";
           %bmp = "Assets/Packs/basic/modules/ctfhud/flag-icon.png:00ff02ff";
           break;
       case "field":
           %loc = $FlagDropFont ~ Team::Flag::Timer(%team);
           %bmp = $FlagDropIcon0;
           break;
       default:
           %loc = String::escapeFormatting(Client::GetName(%loc));
           %bmp = "Assets/Packs/basic/modules/ctfhud/flag-icon.png:fdff00ff";
           break;
   }
   ModernHUD::markup(%x + 55, %y + 8, 445, "<f:font-nostroke.pft:807b00ff:807b00ff:1,1>" ~ %loc, 255);
   ModernHUD::markup(%x + 55, %y + 8, 445, "<f:font-stroke.pft:fff500ff>" ~ %loc, 255);

   ModernHUD::markup(%x + 0, %y + 1, 500, "<b3,3:"~%bmp~">", 255);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally CTFHUD::Update)
function basic::CTFHUD::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
       %score0 = Team::Score(Team::Friendly());
       %score1 = Team::Score(Team::Enemy());
   basic::CTFHUD::FriendlyTeamValue(%team);
   basic::CTFHUD::EnemyTeamValue(%team);
   ModernHUD::markup(%x + 33, %y + 8, 467, "<f:small-black-stroke.pft:228b01FF:000000ff:1,1>" ~%score0, 255);

   ModernHUD::markup(%x + 33, %y + 32, 467, "<f:small-black-stroke.pft:ff0000FF:000000ff:1,1>" ~%score1, 255);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally FlagFlash)
function basic::FlagFlash(%team)
{
   if (Team::Flag::Timer(%team) < 10) {
       $FlagDropIcon0 = "Assets/Packs/basic/modules/ctfhud/flag-icon.png:00ff02"~$CTFTimerDrop~"";
       $FlagDropIcon1 = "Assets/Packs/basic/modules/ctfhud/flag-icon.png:ff0000"~$CTFTimerDrop~"";
     } else {
       $FlagDropIcon0 = "Assets/Packs/basic/modules/ctfhud/flag-icon.png:ffffff";
       $FlagDropIcon1 = "Assets/Packs/basic/modules/ctfhud/flag-icon.png:ffffff";
     }
}

// from Modules/AmmoHud.acs.cs  (originally GAmmo::Update)
function basic::GAmmo::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   if($Weapon::Ammo < 1) {
       %display = " ";
   } else {
       %display = $Weapon::Ammo;
   }

   if($health == 0 || $playingdemo || Client::GetTeam(getManagerId()) == -1) {
       %display = "";
   }



   ModernHUD::markup(%x + 0, %y + 0, 100, "<jc><f:white-default.pft:00cfffff:006880c8:2,2>" @ %display, 255);
}

// from Modules/aHENum/Energy.acs.cs  (originally GEnergy::Update)
function basic::GEnergy::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
       if ( $energy < 35 ) {
           ModernHUD::markup(%x + 0, %y + 0, 100, "<jc><f:small-black-stroke.pft:ff0000ff:000000ff:1,1>" @ $energy, 255);
       } else {
           ModernHUD::markup(%x + 0, %y + 0, 100, "<jc><f:small-black-stroke.pft:ffffffff:000000ff:1,1>" @ $energy, 255);
       }


}

// from Modules/aHENum/Health.acs.cs  (originally GHealth::Update)
function basic::GHealth::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
       if ( $health > 66 ) {
           ModernHUD::markup(%x + 0, %y + 0, 100, "<jc><f:small-black-stroke.pft:ffffffff:000000ff:1,1>" @ $health, 255);
       } else if ( $health > 32 ) {
           ModernHUD::markup(%x + 0, %y + 0, 100, "<jc><f:small-black-stroke.pft:fff000ff:000000ff:1,1>" @ $health, 255);
       } else {
           ModernHUD::markup(%x + 0, %y + 0, 100, "<jc><f:small-black-stroke.pft:ff0000:000000ff:1,1>" @ $health, 255);
       }


}

// from Modules/aHENum/Speed.acs.cs  (originally GSpeed::Update)
function basic::GSpeed::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 0, 50, "<f8>" @ $speed, 255);
}

// from Modules/ItemHUD/ItemHUD.acs.cs  (originally ItemHUD::Update)
function basic::ItemHUD::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;



   %text = "";
   %kits = getItemCount("Repair Kit");
   %Grenades = getItemCount("Grenade");



   $ItemHUD::Kits = %kits;
   $ItemHUD::Grenades = %Grenades;

   %kits = ( %kits > 0 ) ? "Assets/Packs/basic/modules/itemhud/kitdot.png" : "Assets/Packs/basic/modules/itemhud/blankdot.png";

   %text = "<B0,0:" @ %kits @ ">";
   for ( %i = 0; %i < %Grenades; %i++ )
       %text = %text @ "<B0,0:Assets/Packs/basic/modules/itemhud/grendot.png>";

   ModernHUD::markup(%x + 0, %y + 0, 100, %text, 255);
}

// from Modules/fpsHUD/LegendzFPSHUD.acs.cs  (originally TimeFPS::Update)
function basic::TimeFPS::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   %fps ="<f2> FPS:<f3> " @ floor($ConsoleWorld::FrameRate)@"";
   ModernHUD::markup(%x + 0, %y + 1, 100, %fps, 255);
}

// from Modules/ToastyHUD.acs.cs  (originally ToastyHUD::GetImageAndSound)
function basic::ToastyHUD::GetImageAndSound()
{
   // ★Gated.★ Legacy parked this 405x405 art off the right edge and slid it in;
   // drawing it unconditionally puts a permanent Dan Forden on the HUD, and
   // parking it offscreen cannot work because fitOnScreen pulls parts back on.
   if($ToastyHUD::ShowUntil == "" || getSimTime() > $ToastyHUD::ShowUntil)
      return;
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   if(!$pref::ToastyCustomMode) {

       if($IMAGE_NAME == "")
           $IMAGE_NAME = "Assets/Packs/basic/modules/toastyhud/toasty.png";


       if($SND_NAME == "")
           $SND_NAME = "mk.toasty.ogg";
   }


   // A custom $IMAGE_NAME (pref::ToastyCustomMode) is still a bare filename
   // relative to Modules/ToastyHUD/; the pack default is already a full path.
   if(String::findSubStr($IMAGE_NAME, "Assets/Packs/") == 0)
       %img = $IMAGE_NAME;
   else
       %img = "Modules/ToastyHUD/" @ $IMAGE_NAME;
   ModernHUD::markup(%x + 0, %y + 0, 405, "<B0,0:" @ %img @ ">", 255);
}

// from Modules/ToastyHUD.acs.cs  (originally ToastyHUD::Trigger)
function basic::ToastyHUD::Trigger(%msg)
{
   if($playingDemo)
      return;
   if(String::findSubStr(%msg, "mid-air") == -1)
      return;
   // Legacy walked words until one was numeric; getWord past the end returns
   // the literal "-1", which is what ends the walk.
   %meters = -1;
   for(%i = 0; String::Trim(getWord(%msg, %i)) != -1; %i++)
   {
      %w = getWord(%msg, %i);
      if(chr(%w) == "")
      {
         %meters = %w;
         break;
      }
   }
   if(%meters < 50)
      return;
   $ToastyHUD::ShowUntil = getSimTime() + 1400;
   $ToastyHUD::PTotal++;
}

// Constants the legacy module's Init assigned and its Update reads.
function ModernHUDPack::init()
{
   $ItemHUD::Awake = true;
}

function ModernHUDPack::draw_CTFHUD_Container(%screen)
{
   %partW = 500;
   %at = ModernHUD::part("ModernHUD::CTFHUD_Container", "top-left", 41, 61, 500, 72, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from basic::CTFHUD::EnemyTeamValue, basic::CTFHUD::FriendlyTeamValue, basic::CTFHUD::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   basic::CTFHUD::Update();
}

function ModernHUDPack::draw_GAmmo_Container(%screen)
{
   %partW = 100;
   %at = ModernHUD::part("ModernHUD::GAmmo_Container", "bottom-center", 29, 67, 100, 50, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from basic::GAmmo::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   basic::GAmmo::Update();
}

function ModernHUDPack::draw_GEnergy_Container(%screen)
{
   %partW = 100;
   %at = ModernHUD::part("ModernHUD::GEnergy_Container", "top-left", 38, 34, 100, 20, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from basic::GEnergy::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   basic::GEnergy::Update();
}

function ModernHUDPack::draw_GHealth_Container(%screen)
{
   %partW = 100;
   %at = ModernHUD::part("ModernHUD::GHealth_Container", "top-left", 38, 11, 100, 20, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from basic::GHealth::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   basic::GHealth::Update();
}

function ModernHUDPack::draw_GSpeed_Container(%screen)
{
   %partW = 50;
   %at = ModernHUD::part("ModernHUD::GSpeed_Container", "bottom-right", 74, 27, 50, 20, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from basic::GSpeed::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   basic::GSpeed::Update();
}

function ModernHUDPack::draw_ItemHUD_Container(%screen)
{
   %partW = 100;
   %at = ModernHUD::part("ModernHUD::ItemHUD_Container", "bottom-center", 24, 132, 100, 50, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from basic::ItemHUD::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   basic::ItemHUD::Update();
}

function ModernHUDPack::draw_LegendzFPSHUD_Container(%screen)
{
   %partW = 106;
   %at = ModernHUD::part("ModernHUD::LegendzFPSHUD_Container", "top-right", 0, 4, 106, 26, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from basic::TimeFPS::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   basic::TimeFPS::Update();
}

function ModernHUDPack::draw_ToastyHUD_Container(%screen)
{
   %partW = 405;
   %at = ModernHUD::part("ModernHUD::ToastyHUD_Container", "bottom-right", 0, 40, 405, 405, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from basic::ToastyHUD::GetImageAndSound
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   basic::ToastyHUD::GetImageAndSound();
}

function ModernHUDPack::draw(%screen)
{
   ModernHUDPack::detachRetained();

   if(ModernHUDPack::ownsSlot($pref::HudSlot::ctf))
      ModernHUDPack::draw_CTFHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::CTFHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::weapon))
      ModernHUDPack::draw_GAmmo_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GAmmo_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      ModernHUDPack::draw_GEnergy_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GEnergy_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      ModernHUDPack::draw_GHealth_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GHealth_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      ModernHUDPack::draw_GSpeed_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GSpeed_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::items))
      ModernHUDPack::draw_ItemHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ItemHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::fps))
      ModernHUDPack::draw_LegendzFPSHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::LegendzFPSHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::toasty))
      ModernHUDPack::draw_ToastyHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ToastyHUD_Container");
}

function ModernHUDPack::onGuiOpen(%gui)
{
   if(%gui == "playGui")
   {
      Schedule::Add("ModernHUDPack::detachRetained();", 0);
      Schedule::Add("ModernHUDPack::stockHuds();", 0);
   }
}

Event::Attach(eventGuiOpen, ModernHUDPack::onGuiOpen);
ModernHUD::attach("eventServerMessage", "basic::ToastyHUD::Trigger");
ModernHUDPack::prefs();
ModernHUDPack::stockHuds();
ModernHUDPack::init();
ModernHUDPack::detachRetained();
$ModernHUD::LoadComplete = "basic";
