// GENERATED by tools/modernhud_pack.py -- DO NOT EDIT.
// pack: basic  (Basic)
// source of truth: config/ModernHUD/Packs/basic/pack.json
// format 2, generator 3, framework 2
//
// Regenerate with:
//   python tools/modernhud_pack.py --generate config/ModernHUD/Packs/basic/pack.json
// Hand edits are lost. To hand-author instead, set the manifest's
// "authoring" to "manual" -- the generator then refuses to overwrite.

exec("ModernHUD/Framework.cs");
exec("ModernHUD/Packs/basic/components.cs");   // borrowable parts (HUD designer mix-and-match)

$ModernHUD::Enabled = true;
$ModernHUD::Pack = "Basic";
$ModernHUD::PackId = "basic";

// A part is ours unless the player selected another pack's module for its
// slot. ModernHUD is immediate-mode, so hiding retained controls cannot
// disable one of our parts -- the draw dispatch must yield the slot.
function ModernHUDPack::ownsSlot(%value)
{
   if(%value == "")
      return true;
   if(%value == "off")
      return false;
   return String::findSubStr(%value, "Basic::") == 0;
}

// Remove the retained containers these parts replace. Detaching (rather
// than only hiding) leaves exactly one movable identity per component and
// stops the old control from eating K-editor clicks.
function ModernHUDPack::detachRetained()
{
   ModernHUD::detachContainer("CTFHUD::Container");
   ModernHUD::detachContainer("GAmmo::Container");
   ModernHUD::detachContainer("GEnergy::Container");
   ModernHUD::detachContainer("GHealth::Container");
   ModernHUD::detachContainer("GSpeed::Container");
   ModernHUD::detachContainer("ItemHUD::Container");
   ModernHUD::detachContainer("LegendzFPSHUD::Container");
   ModernHUD::detachContainer("ToastyHUD::Container");
}

// The pack's own stock-HUD preferences (minimap shape/size, stock hud
// placement). Applied on load, as the legacy loader does for a legacy pack.
function ModernHUDPack::prefs()
{
   $pref::hudPositionsAmmoHUD::Container = "15 938||0.00885 0.933333 0";
   $pref::hudPositionsclock::Container = "899 16||0.510795 0.015534 0";
   $pref::hudPositionsCtfHUD::Container = "||";
   $pref::hudPositionsElephant::Container = "1719 927||0.987931 0.996774 0";
   $pref::hudPositionsEnemy_Hud = "17 661||0.009884 0.847436 0";
   $pref::hudPositionsFlagCheck::Container = "763 959||0.486624 0.904717 0";
   $pref::hudPositionsFlagPopup::Container = "606 67||0.507963 0.063931 0";
   $pref::hudPositionsGAmmo::Container = "||";
   $pref::hudPositionsGEnergy::Container = "||";
   $pref::hudPositionsGHealth::Container = "||";
   $pref::hudPositionsGSpeed::Container = "||";
   $pref::hudPositionsHitCG1_Hud = "930 510||0 0 0";
   $pref::hudPositionsHUDOverlay::Container = "18 8||0.011688 0.011429 0";
   $pref::hudPositionsItemHUD::Container = "||";
   $pref::hudPositionsLegendzFPSHUD::Container = "||";
   $pref::hudPositionsLiuKangCap::Container = "0 565||-1 0 0";
   $pref::hudPositionsRatingsHUD::Container = "1695 990||1 1 0";
   $pref::hudPositionsScorpionCap::Container = "362 626||0.217548 0.739079 0";
   $pref::hudPositionsToastyHUD::Container = "||";
   $pref::miniMapAlpha = "1";
   $pref::miniMapAutosize = "False";
   $pref::miniMapRotate = "True";
   $pref::miniMapSquare = "False";
   $pref::miniMapWidth = "300";
   $pref::miniMapZoom = "1.75";
}

// The legacy config's config\Modules\guistuff_prefs.acs.cs values. Borrowed
// client-wide globals: snapshot once, put back by restore() on unload.
function ModernHUDPack::mj()
{
   if($ModernHUD::MjSaved != "basic")
   {
      $ModernHUD::MjSaved = "basic";
      $ModernHUD::MjSav::greenlines = $mj::greenlines;
      $ModernHUD::MjSav::shownames = $mj::shownames;
      $ModernHUD::MjSav::showhpbars = $mj::showhpbars;
      $ModernHUD::MjSav::showjetbars = $mj::showjetbars;
      $ModernHUD::MjSav::showhptext = $mj::showhptext;
      $ModernHUD::MjSav::barscrouch = $mj::barscrouch;
      $ModernHUD::MjSav::passhelper = $mj::passhelper;
      $ModernHUD::MjSav::passhelpermm = $mj::passhelpermm;
      $ModernHUD::MjSav::fontdefault = $mj::fontdefault;
      $ModernHUD::MjSav::fontpass = $mj::fontpass;
      $ModernHUD::MjSav::bar_width = $mj::bar_width;
      $ModernHUD::MjSav::bar_height = $mj::bar_height;
      $ModernHUD::MjSav::bar_border_width = $mj::bar_border_width;
      $ModernHUD::MjSav::DrawWeapon = $mj::DrawWeapon;
      $ModernHUD::MjSav::WeaponAlpha = $mj::WeaponAlpha;
   }
   $mj::greenlines = "false";
   $mj::shownames = "true";
   $mj::showhpbars = "False";
   $mj::showjetbars = "False";
   $mj::showhptext = "true";
   $mj::barscrouch = "false";
   $mj::passhelper = "true";
   $mj::passhelpermm = "true";
   $mj::fontdefault = "sf_white_10b.pft";
   $mj::fontpass = "if_g_10b.pft";
   $mj::bar_width = "20";
   $mj::bar_height = "5";
   $mj::bar_border_width = "1";
   $mj::DrawWeapon = "1";
   $mj::WeaponAlpha = "2";
}

function ModernHUDPack::restore()
{
   if($ModernHUD::MjSaved != "basic")
      return;
   $mj::greenlines = $ModernHUD::MjSav::greenlines;
   $mj::shownames = $ModernHUD::MjSav::shownames;
   $mj::showhpbars = $ModernHUD::MjSav::showhpbars;
   $mj::showjetbars = $ModernHUD::MjSav::showjetbars;
   $mj::showhptext = $ModernHUD::MjSav::showhptext;
   $mj::barscrouch = $ModernHUD::MjSav::barscrouch;
   $mj::passhelper = $ModernHUD::MjSav::passhelper;
   $mj::passhelpermm = $ModernHUD::MjSav::passhelpermm;
   $mj::fontdefault = $ModernHUD::MjSav::fontdefault;
   $mj::fontpass = $ModernHUD::MjSav::fontpass;
   $mj::bar_width = $ModernHUD::MjSav::bar_width;
   $mj::bar_height = $ModernHUD::MjSav::bar_height;
   $mj::bar_border_width = $ModernHUD::MjSav::bar_border_width;
   $mj::DrawWeapon = $ModernHUD::MjSav::DrawWeapon;
   $mj::WeaponAlpha = $ModernHUD::MjSav::WeaponAlpha;
   $ModernHUD::MjSaved = "";
}

function ModernHUDPack::stockHuds()
{
   // Visibility only -- placement rides the stock huds' own
   // $pref::hudPositions entries, which the engine re-anchors.
   //
   // ModernHUD::stock is Control::SetVisible with a player row in front
   // of it: the value here is this pack's DEFAULT, and the K panel's row
   // overrides it. Controls outside STOCK_PLAYER_ROWS keep the direct
   // call -- see the note on that list in this generator.
   Control::SetVisible(crosshairHud, true);
   ModernHUD::stock(clockHud, true);
   ModernHUD::stock(sensorHUD, false);
   ModernHUD::stock(compassHud, false);
   ModernHUD::stock(jetPackHud, true);
   ModernHUD::stock(healthHud, true);
   ModernHUD::stock(weaponHud, false);
   ModernHUD::stock(chatDisplayHud, true);
   ModernHUD::stock(Minimap, true);
   Control::SetVisible(reticleCompass, false);
}

ModernHUD::require("ModernHUD/Core/Data/Team.cs");
ModernHUD::require("ModernHUD/Core/Data/Timer.cs");
function ModernHUDPack::init()
{
   basic::compInit();
}

function ModernHUDPack::draw(%screen)
{
   ModernHUDPack::detachRetained();

   if(ModernHUDPack::ownsSlot($pref::HudSlot::ctf))
      basic::draw_CTFHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::CTFHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::weapon))
      basic::draw_GAmmo_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GAmmo_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      basic::draw_GEnergy_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GEnergy_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      basic::draw_GHealth_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GHealth_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      basic::draw_GSpeed_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GSpeed_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::items))
      basic::draw_ItemHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ItemHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::fps))
      basic::draw_LegendzFPSHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::LegendzFPSHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::toasty))
      basic::draw_ToastyHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ToastyHUD_Container");
}

function ModernHUDPack::onPlayGuiOpen()
{
   Schedule::Add("ModernHUDPack::detachRetained();", 0);
   Schedule::Add("ModernHUDPack::stockHuds();", 0);
}

ModernHUD::attach("eventGuiOpen_PlayGui", "ModernHUDPack::onPlayGuiOpen");
ModernHUDPack::prefs();
ModernHUDPack::mj();
ModernHUDPack::stockHuds();
basic::compInit();
ModernHUDPack::detachRetained();
$ModernHUD::LoadComplete = "basic";
