///////////////////////////////////////////
//DO NOT EDIT THIS FILE

function dot_op_AttachCmd(%event, %ID, %extra, %CmdToEval, %arg1, %arg2, %arg3, %arg4, %arg5, %arg6, %arg7, %arg8) {

	if(%event == "" || %ID == "" || %extra == "" || %CmdToEval == "") {
		echo("%event.AttachCmd(%ID, %CmdToEval, %arg1, [%arg2 ... %arg8])");
		return;
	}

	if($RM::EventID[%event] == "") {
		$RM::EventID[%event] = 0;
		$RM::EventList = $RM::EventList@" "@%event;
	}

	//Replace all those %1 %2 %3..etc
	%CmdToEval = sprintf(%CmdToEval, %arg1, %arg2, %arg3, %arg4, %arg5, %arg6, %arg7, %arg8);

	if($ShowAttachedCmd)
		echo("AttachCmd[Event "@%event@" | ID "@%ID@" : "@$RM::EventID[%event]@"]: "@%CmdToEval);

	$RM::AttachedPreCmd[%event, $RM::EventID[%event]] = %extra;

	$RM::AttachedCmd[%event, $RM::EventID[%event]] = %CmdToEval;

	$RM::AttachedCmdID[%ID] = "$RM::AttachedCmd["@%event@", "@$RM::EventID[%event]@"]";

	$RM::EventID[%event]++;
}

function dot_op_DeAttachCmd(%ID) {

	if($RM::AttachedCmdID[%ID] != "") {
		eval($RM::AttachedCmdID[%ID]@" = \"DeAttached\";");
		$RM::AttachedCmdID[%ID] = "";
	}
}

function dot_op_ClearCmds(%event) {
	for(%i = 0; %i <= $RM::EventID[%event]; %i++) {
		$RM::AttachedPreCmd[%event, %i] = "";
		$RM::AttachedCmd[%event, %i] = "";
		$RM::AttachedCmdID[%ID] = "";
	}
	$RM::EventID[%event] = 0;
}

function ClearAllCmds() {
	deleteVariables("RM::Attached*");
	deleteVariables("RM::EventI*");
	$RM::EventList = "";
	$RM::AttachCount = 0;
}

ClearAllCmds();

function dot_op_doCmd(%event) {

	for(%i = 0; %i < $RM::EventID[%event]; %i++) {

		%cmd = $RM::AttachedCmd[%event, %i];

		//echo(" "@%i@") "@%cmd);

		%pass = 1;
		if(%cmd == "DeAttached") {
			//do nothing
		}
		else if(%cmd == "") {
			//do nothing
		}
		else {

			%extra = $RM::AttachedPreCmd[%event, %i];

			if(%extra != "") {

				for(%ii = 0; (%w1 = getWord(%extra, %ii)) != -1; %ii++) {
					%ii++;
					%w2 = getWord(%extra, %ii);
					%w2 = Eval("%r=(%w2);");

					if(String::ICompare(%w1, schedule) == 0) {

						schedule("Eval($RM::AttachedCmd["@%event@", "@%i@"]);", %w2);
						%pass = 0;
					}
				}
			}

			if(%pass)
				eval(%cmd);
		}
	}
}

//SERVER WILL CHECK IF CLIENT HAS THE NEEDED FILES LOADED
function remotermCheck(%mngr, %mask) {
	if(%mngr != 2048)
		return;
	echo(%mask);
	if(String::findSubStr(%mask, "$__RM__") == 0) {
		remoteEval(2048, "rmReport", eval("%r=("@%mask@");"));
	}
}


if(!exec(DeusClient))
	$RM_CLIENT_HASERROR = 1;
