// GENERATED by tools/modernhud_pack.py -- DO NOT EDIT.
// pack: xloader  (Tribes 1.40.655 xLoader)
// source of truth: config/ModernHUD/Packs/xloader/pack.json
// format 2, generator 3, framework 2
//
// Regenerate with:
//   python tools/modernhud_pack.py --generate config/ModernHUD/Packs/xloader/pack.json
// Hand edits are lost. To hand-author instead, set the manifest's
// "authoring" to "manual" -- the generator then refuses to overwrite.

exec("ModernHUD/Framework.cs");
exec("ModernHUD/Packs/xloader/components.cs");   // borrowable parts (HUD designer mix-and-match)

$ModernHUD::Enabled = true;
$ModernHUD::Pack = "Tribes 1.40.655 xLoader";
$ModernHUD::PackId = "xloader";

// A part is ours unless the player selected another pack's module for its
// slot. ModernHUD is immediate-mode, so hiding retained controls cannot
// disable one of our parts -- the draw dispatch must yield the slot.
function ModernHUDPack::ownsSlot(%value)
{
   if(%value == "")
      return true;
   if(%value == "off")
      return false;
   return String::findSubStr(%value, "Tribes 1.40.655 xLoader::") == 0;
}

// Remove the retained containers these parts replace. Detaching (rather
// than only hiding) leaves exactly one movable identity per component and
// stops the old control from eating K-editor clicks.
function ModernHUDPack::detachRetained()
{
   ModernHUD::detachContainer("CtfHUD::Container");
   ModernHUD::detachContainer("ItemHUD::Container");
}

// The pack's own stock-HUD preferences (minimap shape/size, stock hud
// placement). Applied on load, as the legacy loader does for a legacy pack.
function ModernHUDPack::prefs()
{
   $pref::hudPositionsCtfHUD::Container = "180 4||0.285714 0.007692 0";
   $pref::hudPositionsItemHUD::Container = "3 567||0.005618 0.964419 0";
   $pref::miniMapAlpha = "1";
   $pref::miniMapAutosize = "True";
   $pref::miniMapRotate = "True";
   $pref::miniMapSquare = "True";
   $pref::miniMapWidth = "168";
   $pref::miniMapZoom = "1.166667";
}

function ModernHUDPack::stockHuds()
{
   // Visibility only -- placement rides the stock huds' own
   // $pref::hudPositions entries, which the engine re-anchors.
   //
   // ModernHUD::stock is Control::SetVisible with a player row in front
   // of it: the value here is this pack's DEFAULT, and the K panel's row
   // overrides it. Controls outside STOCK_PLAYER_ROWS keep the direct
   // call -- see the note on that list in this generator.
   Control::SetVisible(crosshairHud, true);
   ModernHUD::stock(clockHud, true);
   ModernHUD::stock(sensorHUD, false);
   ModernHUD::stock(compassHud, false);
   ModernHUD::stock(jetPackHud, true);
   ModernHUD::stock(healthHud, true);
   ModernHUD::stock(weaponHud, true);
   ModernHUD::stock(chatDisplayHud, true);
   ModernHUD::stock(Minimap, true);
   Control::SetVisible(reticleCompass, false);
}

ModernHUD::require("ModernHUD/Core/Data/Team.cs");
ModernHUD::require("ModernHUD/Core/Data/Timer.cs");
function ModernHUDPack::init()
{
   xloader::compInit();
}

function ModernHUDPack::draw(%screen)
{
   ModernHUDPack::detachRetained();

   if(ModernHUDPack::ownsSlot($pref::HudSlot::ctf))
      xloader::draw_CtfHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::CtfHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::items))
      xloader::draw_ItemHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ItemHUD_Container");
}

function ModernHUDPack::onPlayGuiOpen()
{
   Schedule::Add("ModernHUDPack::detachRetained();", 0);
   Schedule::Add("ModernHUDPack::stockHuds();", 0);
}

ModernHUD::attach("eventGuiOpen_PlayGui", "ModernHUDPack::onPlayGuiOpen");
ModernHUDPack::prefs();
ModernHUDPack::stockHuds();
xloader::compInit();
ModernHUDPack::detachRetained();
$ModernHUD::LoadComplete = "xloader";
