// GENERATED by tools/modernhud_pack.py -- DO NOT EDIT.
// pack: xloader  (Tribes 1.40.655 xLoader)
// source of truth: config/ModernHUD/Packs/xloader/pack.json
// format 2, generator 3, framework 2
//
// Regenerate with:
//   python tools/modernhud_pack.py --generate config/ModernHUD/Packs/xloader/pack.json
// Hand edits are lost. To hand-author instead, set the manifest's
// "authoring" to "manual" -- the generator then refuses to overwrite.

exec("ModernHUD/Framework.cs");

$ModernHUD::Enabled = true;
$ModernHUD::Pack = "Tribes 1.40.655 xLoader";
$ModernHUD::PackId = "xloader";

// A part is ours unless the player selected another pack's module for its
// slot. ModernHUD is immediate-mode, so hiding retained controls cannot
// disable one of our parts -- the draw dispatch must yield the slot.
function ModernHUDPack::ownsSlot(%value)
{
   if(%value == "")
      return true;
   if(%value == "off")
      return false;
   return String::findSubStr(%value, "Tribes 1.40.655 xLoader::") == 0;
}

// Remove the retained containers these parts replace. Detaching (rather
// than only hiding) leaves exactly one movable identity per component and
// stops the old control from eating K-editor clicks.
function ModernHUDPack::detachRetained()
{
   ModernHUD::detachContainer("CtfHUD::Container");
   ModernHUD::detachContainer("ItemHUD::Container");
}

// The pack's own stock-HUD preferences (minimap shape/size, stock hud
// placement). Applied on load, as the legacy loader does for a legacy pack.
function ModernHUDPack::prefs()
{
   $pref::hudPositionsCtfHUD::Container = "180 4||0.285714 0.007692 0";
   $pref::hudPositionsItemHUD::Container = "3 567||0.005618 0.964419 0";
   $pref::miniMapAlpha = "1";
   $pref::miniMapAutosize = "True";
   $pref::miniMapRotate = "True";
   $pref::miniMapSquare = "True";
   $pref::miniMapWidth = "168";
   $pref::miniMapZoom = "1.166667";
}

function ModernHUDPack::stockHuds()
{
   // Visibility only -- placement rides the stock huds' own
   // $pref::hudPositions entries, which the engine re-anchors.
   //
   // ModernHUD::stock is Control::SetVisible with a player row in front
   // of it: the value here is this pack's DEFAULT, and the K panel's row
   // overrides it. Controls outside STOCK_PLAYER_ROWS keep the direct
   // call -- see the note on that list in this generator.
   Control::SetVisible(crosshairHud, true);
   ModernHUD::stock(clockHud, true);
   ModernHUD::stock(sensorHUD, false);
   ModernHUD::stock(compassHud, false);
   ModernHUD::stock(jetPackHud, true);
   ModernHUD::stock(healthHud, true);
   ModernHUD::stock(weaponHud, true);
   ModernHUD::stock(chatDisplayHud, true);
   ModernHUD::stock(Minimap, true);
   Control::SetVisible(reticleCompass, false);
}

// ---- helpers carried from the legacy pack -------------------------
// A lifted body calls these; the converted pack does not execute the
// legacy module, so they have to come along or the call resolves to
// nothing and the part renders wrong without erroring.
//
// ★Prefixed with the pack id.★ Five packs define CTFHUD::Update; the
// console has one namespace and a definition outlives the pack that made
// it, so under the original names a leftover handler from a pack that is
// no longer loaded would call OUR body. The originals are recorded below
// each definition.
// from Modules/ItemHUD/ItemHUD.acs.cs  (originally ItemHUD::Update)
function xloader::ItemHUD::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;


   %text = "";
   %kits = getItemCount("Repair Kit");
   %mines = getItemCount("Mine");



   $ItemHUD::Kits = %kits;
   $ItemHUD::Mines = %mines;

   %kits = ( %kits > 0 ) ? "Assets/Packs/xloader/modules/itemhud/kitdot.png" : "Assets/Packs/xloader/modules/itemhud/blankdot.png";

   %text = "<B0,0:" @ %kits @ ">";
   for ( %i = 0; %i < %mines; %i++ )
       %text = %text @ "<B0,0:Assets/Packs/xloader/modules/itemhud/minedot.png>";

   ModernHUD::markup(%x + 0, %y + 0, 140, %text, 255);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally CtfHUD::Row)
function xloader::CtfHUD::Row(%x, %y, %slot, %team)
{
   %score = Team::Score(%team);
   %loc = Team::Flag::Location(%team);
   switch(%loc)
   {
      case "home":
         %text = "<f3>Home";
         %bmp = (%slot == 0) ? "friendly.home.png" : "enemy.home.png";
         break;
      case "field":
         %text = "<f3>Dropped-><f2>" @ Team::Flag::Timer(%team);
         %bmp = (%slot == 0) ? "friendly.empty.png" : "enemy.empty.png";
         break;
      default:
         %text = "<f2>" @ String::escapeFormatting(Client::GetName(%loc));
         %bmp = (%slot == 0) ? "friendly.player.png" : "enemy.player.png";
         break;
   }
   ModernHUD::markup(%x, %y, 20,
                     "<b3,3:Assets/Packs/xloader/modules/ctfhud/" @ %bmp @ ">", 255);
   ModernHUD::markup(%x + 22, %y, 150,
                     "<f3>(<f2>" @ %score @ "<f3>)  " @ %text, 255);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally CtfHUD::Update)
function xloader::CtfHUD::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   // friendly on top, enemy below -- the legacy slot order.
   xloader::CtfHUD::Row(%x, %y, 0, Team::Friendly());
   xloader::CtfHUD::Row(%x, %y + 20, 1, Team::Enemy());
}

// Constants the legacy module's Init assigned and its Update reads.
function ModernHUDPack::init()
{
   $ItemHUD::Awake = true;
}

function ModernHUDPack::draw_CtfHUD_Container(%screen)
{
   %partW = 170;
   %at = ModernHUD::part("ModernHUD::CtfHUD_Container", "top-left", 180, 4, 170, 40, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from xloader::CtfHUD::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   xloader::CtfHUD::Update();
}

function ModernHUDPack::draw_ItemHUD_Container(%screen)
{
   %partW = 140;
   %at = ModernHUD::part("ModernHUD::ItemHUD_Container", "bottom-left", 3, 21, 140, 12, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from xloader::ItemHUD::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   xloader::ItemHUD::Update();
}

function ModernHUDPack::draw(%screen)
{
   ModernHUDPack::detachRetained();

   if(ModernHUDPack::ownsSlot($pref::HudSlot::ctf))
      ModernHUDPack::draw_CtfHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::CtfHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::items))
      ModernHUDPack::draw_ItemHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ItemHUD_Container");
}

function ModernHUDPack::onGuiOpen(%gui)
{
   if(%gui == "playGui")
   {
      Schedule::Add("ModernHUDPack::detachRetained();", 0);
      Schedule::Add("ModernHUDPack::stockHuds();", 0);
   }
}

Event::Attach(eventGuiOpen, ModernHUDPack::onGuiOpen);
ModernHUDPack::prefs();
ModernHUDPack::stockHuds();
ModernHUDPack::init();
ModernHUDPack::detachRetained();
$ModernHUD::LoadComplete = "xloader";
