// GENERATED by tools/modernhud_pack.py -- DO NOT EDIT.
// pack: xloader  (Tribes 1.40.655 xLoader)
// source of truth: config/ModernHUD/Packs/xloader/pack.json
// format 1, generator 1, framework 2
//
// Regenerate with:
//   python tools/modernhud_pack.py --generate config/ModernHUD/Packs/xloader/pack.json
// Hand edits are lost. To hand-author instead, set the manifest's
// "authoring" to "manual" -- the generator then refuses to overwrite.

exec("ModernHUD/Framework.cs");

$ModernHUD::Enabled = true;
$ModernHUD::Pack = "Tribes 1.40.655 xLoader";
$ModernHUD::PackId = "xloader";

// A part is ours unless the player selected another pack's module for its
// slot. ModernHUD is immediate-mode, so hiding retained controls cannot
// disable one of our parts -- the draw dispatch must yield the slot.
function ModernHUDPack::ownsSlot(%value)
{
   if(%value == "")
      return true;
   if(%value == "off")
      return false;
   return String::findSubStr(%value, "Tribes 1.40.655 xLoader::") == 0;
}

// Remove the retained containers these parts replace. Detaching (rather
// than only hiding) leaves exactly one movable identity per component and
// stops the old control from eating K-editor clicks.
function ModernHUDPack::detachRetained()
{
   ModernHUD::detachContainer("ItemHUD::Container");
}

// The pack's own stock-HUD preferences (minimap shape/size, stock hud
// placement). Applied on load, as the legacy loader does for a legacy pack.
function ModernHUDPack::prefs()
{
   $pref::hudPositionsCtfHUD::Container = "180 4||0.285714 0.007692 0";
   $pref::hudPositionsItemHUD::Container = "3 567||0.005618 0.964419 0";
   $pref::miniMapAlpha = "1";
   $pref::miniMapAutosize = "True";
   $pref::miniMapRotate = "True";
   $pref::miniMapSquare = "True";
   $pref::miniMapWidth = "168";
   $pref::miniMapZoom = "1.166667";
}

function ModernHUDPack::stockHuds()
{
   // Visibility only -- placement rides the stock huds' own
   // $pref::hudPositions entries, which the engine re-anchors.
   Control::SetVisible(crosshairHud, true);
   Control::SetVisible(clockHud, true);
   Control::SetVisible(sensorHUD, false);
   Control::SetVisible(compassHud, false);
   Control::SetVisible(jetPackHud, true);
   Control::SetVisible(healthHud, true);
   Control::SetVisible(weaponHud, true);
   Control::SetVisible(chatDisplayHud, true);
   Control::SetVisible(Minimap, true);
   Control::SetVisible(reticleCompass, false);
}

// ---- helpers carried from the legacy pack -------------------------
// A lifted body calls these; the converted pack does not execute the
// legacy module, so they have to come along or the call resolves to
// nothing and the part renders wrong without erroring.
//
// ★Prefixed with the pack id.★ Five packs define CTFHUD::Update; the
// console has one namespace and a definition outlives the pack that made
// it, so under the original names a leftover handler from a pack that is
// no longer loaded would call OUR body. The originals are recorded below
// each definition.
// from Modules/ItemHUD/ItemHUD.acs.cs  (originally ItemHUD::Update)
function xloader::ItemHUD::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;


   %text = "";
   %kits = getItemCount("Repair Kit");
   %mines = getItemCount("Mine");



   $ItemHUD::Kits = %kits;
   $ItemHUD::Mines = %mines;

   %kits = ( %kits > 0 ) ? "Assets/Packs/xloader/modules/itemhud/kitdot.png" : "Assets/Packs/xloader/modules/itemhud/blankdot.png";

   %text = "<B0,0:modules/itemhud/" @ %kits @ ">";
   for ( %i = 0; %i < %mines; %i++ )
       %text = %text @ "<B0,0:Assets/Packs/xloader/modules/itemhud/minedot.png>";

   ModernHUD::markup(%x + 0, %y + 0, 140, %text, 255);
}

// Constants the legacy module's Init assigned and its Update reads.
function ModernHUDPack::init()
{
   $ItemHUD::Awake = true;
}

function ModernHUDPack::draw_ItemHUD_Container(%screen)
{
   %partW = 140;
   %at = ModernHUD::part("ModernHUD::ItemHUD_Container", "bottom-left", 3, 21, 140, 12, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from xloader::ItemHUD::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   xloader::ItemHUD::Update();
}

function ModernHUDPack::draw(%screen)
{
   ModernHUDPack::detachRetained();

   if(ModernHUDPack::ownsSlot($pref::HudSlot::items))
      ModernHUDPack::draw_ItemHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ItemHUD_Container");
}

function ModernHUDPack::onGuiOpen(%gui)
{
   if(%gui == "playGui")
   {
      Schedule::Add("ModernHUDPack::detachRetained();", 0);
      Schedule::Add("ModernHUDPack::stockHuds();", 0);
   }
}

Event::Attach(eventGuiOpen, ModernHUDPack::onGuiOpen);
ModernHUDPack::prefs();
ModernHUDPack::stockHuds();
ModernHUDPack::init();
ModernHUDPack::detachRetained();
