// GENERATED by tools/modernhud_pack.py -- DO NOT EDIT.
// pack: vodka  (Tribes - Minimalist - v0dkA)
// source of truth: config/ModernHUD/Packs/vodka/pack.json
// format 1, generator 2, framework 2
//
// Regenerate with:
//   python tools/modernhud_pack.py --generate config/ModernHUD/Packs/vodka/pack.json
// Hand edits are lost. To hand-author instead, set the manifest's
// "authoring" to "manual" -- the generator then refuses to overwrite.

exec("ModernHUD/Framework.cs");

$ModernHUD::Enabled = true;
$ModernHUD::Pack = "Tribes - Minimalist - v0dkA";
$ModernHUD::PackId = "vodka";

// A part is ours unless the player selected another pack's module for its
// slot. ModernHUD is immediate-mode, so hiding retained controls cannot
// disable one of our parts -- the draw dispatch must yield the slot.
function ModernHUDPack::ownsSlot(%value)
{
   if(%value == "")
      return true;
   if(%value == "off")
      return false;
   return String::findSubStr(%value, "Tribes - Minimalist - v0dkA::") == 0;
}

// Remove the retained containers these parts replace. Detaching (rather
// than only hiding) leaves exactly one movable identity per component and
// stops the old control from eating K-editor clicks.
function ModernHUDPack::detachRetained()
{
   ModernHUD::detachContainer("AmmoHUD::Container");
   ModernHUD::detachContainer("ChatOverlay::Container");
   ModernHUD::detachContainer("clock::Container");
   ModernHUD::detachContainer("CTFHUD::Container");
   ModernHUD::detachContainer("GEnergy::Container");
   ModernHUD::detachContainer("GHealth::Container");
   ModernHUD::detachContainer("GSpeed::Container");
   ModernHUD::detachContainer("LegendzFPSHUD::Container");
   ModernHUD::detachContainer("RadarOverlay::Container");
   ModernHUD::detachContainer("RadarRing::Container");
   ModernHUD::detachContainer("ToastyHUD::Container");
}

// The pack's own stock-HUD preferences (minimap shape/size, stock hud
// placement). Applied on load, as the legacy loader does for a legacy pack.
function ModernHUDPack::prefs()
{
   $pref::hudPositionsaaRepKitHUD::Container = "1358 182||0.717759 0.173004 0";
   $pref::hudPositionsAmmoHUD::Container = "1226 19||0.696195 0.019153 0";
   $pref::hudPositionsChatOverlay::Container = "552 18||0.43949 0.018163 0";
   $pref::hudPositionsclock::Container = "171 4||0.098276 0.003774 0";
   $pref::hudPositionsCtfHUD::Container = "1720 7||1 0.007143 0";
   $pref::hudPositionsElephant::Container = "1740 930||1 1 0";
   $pref::hudPositionsEnemy_Hud = "17 661||0.009884 0.847436 0";
   $pref::hudPositionsFlagCheck::Container = "763 959||0.486624 0.904717 0";
   $pref::hudPositionsFlagPopup::Container = "606 67||0.507963 0.063931 0";
   $pref::hudPositionsGEnergy::Container = "1731 115||0.981293 0.109316 0";
   $pref::hudPositionsGHealth::Container = "1731 90||0.981293 0.085551 0";
   $pref::hudPositionsGSpeed::Container = "1749 947||0.950543 0.901905 0";
   $pref::hudPositionsHitCG1_Hud = "930 510||0 0 0";
   $pref::hudPositionsHUDOverlay::Container = "5 16||0.003102 0.020725 0";
   $pref::hudPositionsItemHUD::Container = "1336 18||0.724119 0.01791 0";
   $pref::hudPositionsLegendzFPSHUD::Container = "27 3||0.014884 0.002846 0";
   $pref::hudPositionsLiuKangCap::Container = "0 565||-1 0 0";
   $pref::hudPositionsRadarOverlay::Container = "5 17||0.003102 0.022021 0";
   $pref::hudPositionsRadarRing::Container = "8 21||0.004938 0.026923 0";
   $pref::hudPositionsRatingsHUD::Container = "1695 990||1 1 0";
   $pref::hudPositionsScorpionCap::Container = "362 626||0.217548 0.739079 0";
   $pref::hudPositionsToastyHUD::Container = "1920 680||1.267327 1.007407 0";
   $pref::miniMapAlpha = "1";
   $pref::miniMapAutosize = "False";
   $pref::miniMapRotate = "True";
   $pref::miniMapSquare = "False";
   $pref::miniMapWidth = "300";
   $pref::miniMapZoom = "1.75";
}

function ModernHUDPack::stockHuds()
{
   // Visibility only -- placement rides the stock huds' own
   // $pref::hudPositions entries, which the engine re-anchors.
   //
   // ModernHUD::stock is Control::SetVisible with a player row in front
   // of it: the value here is this pack's DEFAULT, and the K panel's row
   // overrides it. Controls outside STOCK_PLAYER_ROWS keep the direct
   // call -- see the note on that list in this generator.
   Control::SetVisible(crosshairHud, true);
   ModernHUD::stock(clockHud, false);
   ModernHUD::stock(sensorHUD, false);
   ModernHUD::stock(compassHud, false);
   ModernHUD::stock(jetPackHud, false);
   ModernHUD::stock(healthHud, false);
   ModernHUD::stock(weaponHud, false);
   ModernHUD::stock(chatDisplayHud, true);
   ModernHUD::stock(Minimap, true);
   Control::SetVisible(reticleCompass, false);
}

ModernHUD::require("ModernHUD/Core/Data/Team.cs");
ModernHUD::require("ModernHUD/Core/Data/Timer.cs");

// ---- helpers carried from the legacy pack -------------------------
// A lifted body calls these; the converted pack does not execute the
// legacy module, so they have to come along or the call resolves to
// nothing and the part renders wrong without erroring.
//
// ★Prefixed with the pack id.★ Five packs define CTFHUD::Update; the
// console has one namespace and a definition outlives the pack that made
// it, so under the original names a leftover handler from a pack that is
// no longer loaded would call OUR body. The originals are recorded below
// each definition.
// from Modules/WeaponHUD/AmmoHUD.acs.cs  (originally AmmoHUD::Init)
function vodka::AmmoHUD::Init()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 0, 159, "<B0,0:Assets/Packs/vodka/modules/weaponhud/ammohudbg-50.png>", 255);
}

// from Modules/WeaponHUD/AmmoHUD.acs.cs  (originally AmmoHUD::Update)
function vodka::AmmoHUD::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;

   if($Weapon::Ammo < 0)
       %ammo = "~";
   else
       %ammo = $Weapon::Ammo;

   ModernHUD::markup(%x + 100, %y + 13, 40, "<jc><f:small-black-stroke.pft:ffffffff:000000ff:1,1>" @ %ammo, 255);





   %weapon = getItemDesc(getMountedItem(0));
   if(%weapon == "Disc Launcher")
       %icon = "Assets/Packs/vodka/modules/weaponhud/disc.png";
   else if(%weapon == "Grenade Launcher")
       %icon = "Assets/Packs/vodka/modules/weaponhud/grenade.png";
   else if(%weapon == "Chaingun")
       %icon = "Assets/Packs/vodka/modules/weaponhud/chaingun.png";
   else if(%weapon == "Mortar")
       %icon = "Assets/Packs/vodka/modules/weaponhud/mortar.png";
   else if(%weapon == "Plasma Gun")
       %icon = "Assets/Packs/vodka/modules/weaponhud/plasma.png";
   else if(%weapon == "Laser Rifle")
       %icon = "Assets/Packs/vodka/modules/weaponhud/sniper.png";
   else if(%weapon == "Blaster")
       %icon = "Assets/Packs/vodka/modules/weaponhud/blaster.png";
   else if(%weapon == "ELF Gun")
       %icon = "Assets/Packs/vodka/modules/weaponhud/elf.png";
   else if(%weapon == "Targeting Laser")
       %icon = "Assets/Packs/vodka/modules/weaponhud/target.png";
   else
       %icon = "";

   if(%icon != "")
       ModernHUD::markup(%x + 25, %y + 13, 134, "<B0,0:" @ %icon @ ">", 255);
   else
       ModernHUD::markup(%x + 25, %y + 13, 134, "", 255);

}

// from Modules/ChatOverlay/ChatBorder.acs.cs  (originally ChatOverlay::Init)
function vodka::ChatOverlay::Init()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 0, 664, "<B0,0:Assets/Packs/vodka/modules/chatoverlay/chatbg.png>", 255);
}

// from Modules/gameclock.acs.cs  (originally clock::Iterate)
function vodka::clock::Iterate()
{
   if ($clock::CountingDown)
   {
       if ($clock::Sec > 0)
           $clock::Sec--;
       else
       {
           $clock::Sec = 59;

           if ($clock::Min > 0)
               $clock::Min--;
           else
           {
               $clock::Min = 59;
               $clock::Hour--;
           }
       }
   }
   else
   {
       if ($clock::Sec < 59)
           $clock::Sec++;
       else
       {
           $clock::Sec = 0;

           if ($clock::Min < 59)
               $clock::Min++;
           else
           {
               $clock::Min = 0;
               $clock::Hour++;
           }
       }
   }
   vodka::clock::Update();
   Schedule::Add("vodka::clock::Iterate();", 1);
}

// from Modules/gameclock.acs.cs  (originally clock::Reset)
function vodka::clock::Reset()
{
   $clock::Hour = 0;
   $clock::Min = 0;
   $clock::Sec = 0;
   $clock::CountingDown = false;
   Schedule::Add("vodka::clock::Iterate();", 1);
}

// from Modules/gameclock.acs.cs  (originally clock::SetReverse)
function vodka::clock::SetReverse()
{
   $clock::Hour = $clock::Min = $clock::Sec = 0;
   $clock::CountingDown = false;

   Schedule::Add("vodka::clock::Iterate();", 1);
   vodka::clock::Update();
}

// from Modules/gameclock.acs.cs  (originally clock::Update)
function vodka::clock::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 0, 180, "<jc><f1>" @ ( ( $clock::Hour < 10 ) ? "0" @ $clock::Hour : $clock::Hour ) @ ":" @ ( ( $clock::Min < 10 ) ? "0" @ $clock::Min : $clock::Min ) @ ":" @ ( ( $clock::Sec < 10 ) ? "0" @ $clock::Sec : $clock::Sec ), 255);
}

// from Modules/gameclock.acs.cs  (originally clock::UpdateTime)
function vodka::clock::UpdateTime(%min, %sec)
{
   $clock::Hour = floor(%min / 60);
   $clock::Min = %min % 60;
   $clock::Sec = %sec;
   $clock::CountingDown = true;
   Schedule::Add("vodka::clock::Iterate();", 1);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally CTFHUD::EnemyTeamValue)
function vodka::CTFHUD::EnemyTeamValue(%team, %score1)
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
       %team = Team::Enemy();
   %loc = Team::Flag::Location(Team::Enemy());
   vodka::FlagFlash(%team);

   switch ( %loc ) {
       case "home":
           %loc = "<f:CTFHud-Font.pft>:::::: Home ::::::";
           break;
       case "field":
           %loc = $FlagDropFontE ~ Team::Flag::Timer(%team);
           break;
       default:
           %loc = "<f:CTFHud-Font.pft:3ffd04>" ~ String::escapeFormatting(Client::GetName(%loc));
           break;
   }

   ModernHUD::markup(%x + 16, %y + 56, 178, "<jc>" ~ %loc, 255);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally CTFHUD::FriendlyTeamValue)
function vodka::CTFHUD::FriendlyTeamValue(%team, %score0)
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
       %team = Team::Friendly();
   %loc = Team::Flag::Location(Team::Friendly());
   vodka::FlagFlash(%team);

   switch ( %loc ) {
       case "home":
           %loc = "<f:CTFHud-Font.pft>:::::: Home ::::::";
           break;
       case "field":
           %loc = $FlagDropFontF ~ Team::Flag::Timer(%team);
           break;
       default:
           %loc = "<f:CTFHud-Font.pft:d20808>" ~ String::escapeFormatting(Client::GetName(%loc));
           break;
   }

   ModernHUD::markup(%x + 16, %y + 18, 178, "<jc><f1>" ~ %loc, 255);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally CTFHUD::Init)
function vodka::CTFHUD::Init()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 0, 200, "<b3,3:Assets/Packs/vodka/modules/ctfhud/ctfbg.png:ffffff80>", 255);
   ModernHUD::markup(%x + 14, %y + 5, 186, "<f1>Score:", 255);
   ModernHUD::markup(%x + 14, %y + 43, 186, "<f1>Score:", 255);
   ModernHUD::markup(%x + 14, %y + 18, 186, "<f1>Flag:", 255);
   ModernHUD::markup(%x + 14, %y + 56, 186, "<f1>Flag:", 255);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally CTFHUD::Update)
function vodka::CTFHUD::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
       %score0 = Team::Score(Team::Friendly());
       %score1 = Team::Score(Team::Enemy());
   vodka::CTFHUD::FriendlyTeamValue(%team);
   vodka::CTFHUD::EnemyTeamValue(%team);
   ModernHUD::markup(%x + 64, %y + 5, 136, "<f1>" ~%score0, 255);
   ModernHUD::markup(%x + 64, %y + 43, 136, "<f1>" ~%score1, 255);
}

// from Modules/CTFHud/CTFHud.acs.cs  (originally FlagFlash)
function vodka::FlagFlash(%team)
{
   if (Team::Flag::Timer(%team) < 10) {
       $FlagDropFontE = "<f:CTFHud-Font.pft:ff0000"~$CTFTimerDropID~":ffffff>";
       $FlagDropFontF = "<f:CTFHud-Font.pft:3ffd04"~$CTFTimerDropID~":ffffff>";
     } else {
       $FlagDropFontE = "<f:CTFHud-Font.pft:FFFFFF>";
       $FlagDropFontF = "<f:CTFHud-Font.pft:FFFFFF>";
     }
}

// from Modules/HeEnHUD/Energy.acs.cs  (originally GEnergy::Init)
function vodka::GEnergy::Init()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 0, 156, "<B0,0:Assets/Packs/vodka/modules/heenhud/frame.png>", 255);
}

// from Modules/HeEnHUD/Health.acs.cs  (originally GHealth::Init)
function vodka::GHealth::Init()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 0, 156, "<B0,0:Assets/Packs/vodka/modules/heenhud/frame.png>", 255);
}

// from Modules/HeEnHUD/Speed.acs.cs  (originally GSpeed::Update)
function vodka::GSpeed::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 5, 80, "<jc><f:Speed-Font.pft:ffc600FF>" @ $speed, 255);
}

// from Modules/WeaponHUD/AmmoHUD.acs.cs  (originally ItemHUD::Update)
function vodka::ItemHUD::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;


   %Gren = getItemCount("Grenade");
   %Beac = getItemCount("Beacon");
   %RKit = getItemCount("Repair Kit");


   $ItemHUD::RKit = %RKit;
   $ItemHUD::Gren = %Gren;
   $ItemHUD::Beac = %Beac;





   %countFont = "<jc><f:small-black-stroke.pft:ffffffff:000000ff:1,1>";
   %GrenadeTxt = %countFont @ %Gren;
   %BeaconTxt = %countFont @ %Beac;
   %RepKitTxt = %countFont @ %RKit;

     ModernHUD::markup(%x + 15, %y + 53, 144, "<B0,0:Assets/Packs/vodka/modules/weaponhud/repkit.png>", 255);
     ModernHUD::markup(%x + 34, %y + 53, 30, %RepKitTxt, 255);

     ModernHUD::markup(%x + 96, %y + 53, 63, " <B0,0:Assets/Packs/vodka/modules/weaponhud/gren.png>", 255);
     ModernHUD::markup(%x + 119, %y + 53, 30, %GrenadeTxt, 255);

     ModernHUD::markup(%x + 51, %y + 53, 108, " <B0,0:Assets/Packs/vodka/modules/weaponhud/beacon.png>", 255);
     ModernHUD::markup(%x + 76, %y + 53, 30, %BeaconTxt, 255);
}

// from Modules/minimap/RadarBorder.acs.cs  (originally RadarOverlay::Init)
function vodka::RadarOverlay::Init()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 0, 308, "<B0,0:Assets/Packs/vodka/modules/minimap/radar.png:keyblack>", 255);
}

// from Modules/minimap/RadarRing.acs.cs  (originally RadarRing::Init)
function vodka::RadarRing::Init()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   ModernHUD::markup(%x + 0, %y + 0, 300, "<B0,0:Assets/Packs/vodka/modules/minimap/ring.png>", 255);
}

// from Modules/fpsHUD/LegendzFPSHUD.acs.cs  (originally TimeFPS::Update)
function vodka::TimeFPS::Update()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   %fps ="<f2> FPS:<f:FPS-Font.pft:ffde00> " @ floor($ConsoleWorld::FrameRate)@"";
   ModernHUD::markup(%x + 0, %y + 1, 100, %fps, 255);
}

// from Modules/ToastyHUD.acs.cs  (originally ToastyHUD::GetImageAndSound)
function vodka::ToastyHUD::GetImageAndSound()
{
   %x = $ModernHUD::PartX;
   %y = $ModernHUD::PartY;
   if(!$pref::ToastyCustomMode) {

       if($IMAGE_NAME == "")
           $IMAGE_NAME = "Assets/Packs/vodka/modules/toastyhud/toasty.png";


       if($SND_NAME == "")
           $SND_NAME = "mk.toasty.ogg";
   }


   // A custom $IMAGE_NAME (pref::ToastyCustomMode) is still a bare filename
   // relative to Modules/ToastyHUD/; the pack default is already a full path.
   if(String::findSubStr($IMAGE_NAME, "Assets/Packs/") == 0)
       %img = $IMAGE_NAME;
   else
       %img = "Modules/ToastyHUD/" @ $IMAGE_NAME;
   ModernHUD::markup(%x + 0, %y + 0, 405, "<B0,0:" @ %img @ ">", 255);
}

// Constants the legacy module's Init assigned and its Update reads.
function ModernHUDPack::init()
{
   $AmmoHUD::Loaded = true;
   $AmmoHUD::Awake = false;
   $ItemHUD::RKit = -1;
   $ItemHUD::Gren = -1;
   $ItemHUD::Beac = -1;
   $AmmoHUD::Awake = true;
   $CTFHUD::Loaded = true;
   $CTFTimerDropID = xFont::NewTimer("CTFTimerDrop", 0, 255, 25, 0.05, 0);
}

function ModernHUDPack::draw_AmmoHUD_Container(%screen)
{
   %partW = 159;
   %at = ModernHUD::part("ModernHUD::AmmoHUD_Container", "top-center", 346, 19, 159, 88, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from vodka::AmmoHUD::Init, vodka::AmmoHUD::Update, vodka::ItemHUD::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::AmmoHUD::Init();
   vodka::AmmoHUD::Update();
   vodka::ItemHUD::Update();
}

function ModernHUDPack::draw_ChatOverlay_Container(%screen)
{
   %partW = 664;
   %at = ModernHUD::part("ModernHUD::ChatOverlay_Container", "top-center", -76, 18, 664, 89, %screen);
   %at = ModernHUD::dockTo("ModernHUD::ChatOverlay_Container", "chatDisplayHud", -7, -5, %at, 664, 89);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from vodka::ChatOverlay::Init
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::ChatOverlay::Init();
}

function ModernHUDPack::draw_clock_Container(%screen)
{
   %partW = 180;
   %at = ModernHUD::part("ModernHUD::clock_Container", "top-left", 171, 4, 180, 20, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from vodka::clock::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::clock::Update();
}

function ModernHUDPack::draw_CTFHUD_Container(%screen)
{
   %partW = 200;
   %at = ModernHUD::part("ModernHUD::CTFHUD_Container", "top-right", 0, 7, 200, 100, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from vodka::CTFHUD::EnemyTeamValue, vodka::CTFHUD::FriendlyTeamValue, vodka::CTFHUD::Init, vodka::CTFHUD::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::CTFHUD::Init();
   vodka::CTFHUD::Update();
}

function ModernHUDPack::draw_GEnergy_Container(%screen)
{
   %partW = 156;
   %at = ModernHUD::part("ModernHUD::GEnergy_Container", "top-right", 33, 115, 156, 28, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   ModernHUD::bar(%x + 11, %y + 11, $energy*1.35, 7, "Assets/Packs/vodka/modules/heenhud/energybar.png", 255);
   // lifted verbatim from vodka::GEnergy::Init
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::GEnergy::Init();
}

function ModernHUDPack::draw_GHealth_Container(%screen)
{
   %partW = 156;
   %at = ModernHUD::part("ModernHUD::GHealth_Container", "top-right", 33, 90, 156, 28, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   ModernHUD::bar(%x + 11, %y + 11, $health*1.35, 7, "Assets/Packs/vodka/modules/heenhud/healthbar.png", 255);
   // lifted verbatim from vodka::GHealth::Init
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::GHealth::Init();
}

function ModernHUDPack::draw_GSpeed_Container(%screen)
{
   %partW = 80;
   %at = ModernHUD::part("ModernHUD::GSpeed_Container", "bottom-right", 91, 103, 80, 30, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from vodka::GSpeed::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::GSpeed::Update();
}

function ModernHUDPack::draw_LegendzFPSHUD_Container(%screen)
{
   %partW = 106;
   %at = ModernHUD::part("ModernHUD::LegendzFPSHUD_Container", "top-left", 27, 3, 106, 26, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from vodka::TimeFPS::Update
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::TimeFPS::Update();
}

function ModernHUDPack::draw_RadarOverlay_Container(%screen)
{
   %partW = 308;
   %at = ModernHUD::part("ModernHUD::RadarOverlay_Container", "top-left", 5, 17, 308, 308, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from vodka::RadarOverlay::Init
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::RadarOverlay::Init();
}

function ModernHUDPack::draw_RadarRing_Container(%screen)
{
   %partW = 300;
   %at = ModernHUD::part("ModernHUD::RadarRing_Container", "top-left", 8, 21, 300, 300, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from vodka::RadarRing::Init
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::RadarRing::Init();
}

function ModernHUDPack::draw_ToastyHUD_Container(%screen)
{
   %partW = 405;
   %at = ModernHUD::part("ModernHUD::ToastyHUD_Container", "bottom-right", -405, -5, 405, 405, %screen);
   %x = getWord(%at, 0);
   %y = getWord(%at, 1);
   // lifted verbatim from vodka::ToastyHUD::GetImageAndSound
   $ModernHUD::PartX = %x;
   $ModernHUD::PartY = %y;
   vodka::ToastyHUD::GetImageAndSound();
}

function ModernHUDPack::draw(%screen)
{
   ModernHUDPack::detachRetained();

   if(ModernHUDPack::ownsSlot($pref::HudSlot::weapon))
      ModernHUDPack::draw_AmmoHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::AmmoHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::chat))
      ModernHUDPack::draw_ChatOverlay_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ChatOverlay_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::clock))
      ModernHUDPack::draw_clock_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::clock_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::ctf))
      ModernHUDPack::draw_CTFHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::CTFHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      ModernHUDPack::draw_GEnergy_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GEnergy_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      ModernHUDPack::draw_GHealth_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GHealth_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      ModernHUDPack::draw_GSpeed_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GSpeed_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::fps))
      ModernHUDPack::draw_LegendzFPSHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::LegendzFPSHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::minimap))
      ModernHUDPack::draw_RadarOverlay_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::RadarOverlay_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::minimap))
      ModernHUDPack::draw_RadarRing_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::RadarRing_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::toasty))
      ModernHUDPack::draw_ToastyHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ToastyHUD_Container");
}

function ModernHUDPack::onGuiOpen(%gui)
{
   if(%gui == "playGui")
   {
      Schedule::Add("ModernHUDPack::detachRetained();", 0);
      Schedule::Add("ModernHUDPack::stockHuds();", 0);
   }
}

Event::Attach(eventGuiOpen, ModernHUDPack::onGuiOpen);
ModernHUD::attach("eventConnected", "vodka::clock::Reset");
ModernHUD::attach("eventMatchStarted", "vodka::clock::SetReverse");
ModernHUD::attach("eventUpdateTime", "vodka::clock::UpdateTime");
ModernHUDPack::prefs();
ModernHUDPack::stockHuds();
ModernHUDPack::init();
ModernHUDPack::detachRetained();
