// GENERATED by tools/modernhud_pack.py -- DO NOT EDIT.
// pack: vodka  (Tribes - Minimalist - v0dkA)
// source of truth: config/ModernHUD/Packs/vodka/pack.json
// format 2, generator 3, framework 2
//
// Regenerate with:
//   python tools/modernhud_pack.py --generate config/ModernHUD/Packs/vodka/pack.json
// Hand edits are lost. To hand-author instead, set the manifest's
// "authoring" to "manual" -- the generator then refuses to overwrite.

exec("ModernHUD/Framework.cs");
exec("ModernHUD/Packs/vodka/components.cs");   // borrowable parts (HUD designer mix-and-match)

$ModernHUD::Enabled = true;
$ModernHUD::Pack = "Tribes - Minimalist - v0dkA";
$ModernHUD::PackId = "vodka";

// A part is ours unless the player selected another pack's module for its
// slot. ModernHUD is immediate-mode, so hiding retained controls cannot
// disable one of our parts -- the draw dispatch must yield the slot.
function ModernHUDPack::ownsSlot(%value)
{
   if(%value == "")
      return true;
   if(%value == "off")
      return false;
   return String::findSubStr(%value, "Tribes - Minimalist - v0dkA::") == 0;
}

// Remove the retained containers these parts replace. Detaching (rather
// than only hiding) leaves exactly one movable identity per component and
// stops the old control from eating K-editor clicks.
function ModernHUDPack::detachRetained()
{
   ModernHUD::detachContainer("AmmoHUD::Container");
   ModernHUD::detachContainer("ChatOverlay::Container");
   ModernHUD::detachContainer("clock::Container");
   ModernHUD::detachContainer("CTFHUD::Container");
   ModernHUD::detachContainer("GEnergy::Container");
   ModernHUD::detachContainer("GHealth::Container");
   ModernHUD::detachContainer("GSpeed::Container");
   ModernHUD::detachContainer("LegendzFPSHUD::Container");
   ModernHUD::detachContainer("RadarOverlay::Container");
   ModernHUD::detachContainer("RadarRing::Container");
   ModernHUD::detachContainer("ToastyHUD::Container");
}

// The pack's own stock-HUD preferences (minimap shape/size, stock hud
// placement). Applied on load, as the legacy loader does for a legacy pack.
function ModernHUDPack::prefs()
{
   $pref::hudPositionsaaRepKitHUD::Container = "1358 182||0.717759 0.173004 0";
   $pref::hudPositionsAmmoHUD::Container = "1226 19||0.696195 0.019153 0";
   $pref::hudPositionsChatOverlay::Container = "552 18||0.43949 0.018163 0";
   $pref::hudPositionsclock::Container = "171 4||0.098276 0.003774 0";
   $pref::hudPositionsCtfHUD::Container = "1720 7||1 0.007143 0";
   $pref::hudPositionsElephant::Container = "1740 930||1 1 0";
   $pref::hudPositionsEnemy_Hud = "17 661||0.009884 0.847436 0";
   $pref::hudPositionsFlagCheck::Container = "763 959||0.486624 0.904717 0";
   $pref::hudPositionsFlagPopup::Container = "606 67||0.507963 0.063931 0";
   $pref::hudPositionsGEnergy::Container = "1731 115||0.981293 0.109316 0";
   $pref::hudPositionsGHealth::Container = "1731 90||0.981293 0.085551 0";
   $pref::hudPositionsGSpeed::Container = "1749 947||0.950543 0.901905 0";
   $pref::hudPositionsHitCG1_Hud = "930 510||0 0 0";
   $pref::hudPositionsHUDOverlay::Container = "5 16||0.003102 0.020725 0";
   $pref::hudPositionsItemHUD::Container = "1336 18||0.724119 0.01791 0";
   $pref::hudPositionsLegendzFPSHUD::Container = "27 3||0.014884 0.002846 0";
   $pref::hudPositionsLiuKangCap::Container = "0 565||-1 0 0";
   $pref::hudPositionsRadarOverlay::Container = "5 17||0.003102 0.022021 0";
   $pref::hudPositionsRadarRing::Container = "8 21||0.004938 0.026923 0";
   $pref::hudPositionsRatingsHUD::Container = "1695 990||1 1 0";
   $pref::hudPositionsScorpionCap::Container = "362 626||0.217548 0.739079 0";
   $pref::hudPositionsToastyHUD::Container = "1920 680||1.267327 1.007407 0";
   $pref::miniMapAlpha = "1";
   $pref::miniMapAutosize = "False";
   $pref::miniMapRotate = "True";
   $pref::miniMapSquare = "False";
   $pref::miniMapWidth = "300";
   $pref::miniMapZoom = "1.75";
}

// The legacy config's config\Modules\guistuff_prefs.acs.cs values. Borrowed
// client-wide globals: snapshot once, put back by restore() on unload.
function ModernHUDPack::mj()
{
   if($ModernHUD::MjSaved != "vodka")
   {
      $ModernHUD::MjSaved = "vodka";
      $ModernHUD::MjSav::greenlines = $mj::greenlines;
      $ModernHUD::MjSav::shownames = $mj::shownames;
      $ModernHUD::MjSav::showhpbars = $mj::showhpbars;
      $ModernHUD::MjSav::showjetbars = $mj::showjetbars;
      $ModernHUD::MjSav::showhptext = $mj::showhptext;
      $ModernHUD::MjSav::barscrouch = $mj::barscrouch;
      $ModernHUD::MjSav::passhelper = $mj::passhelper;
      $ModernHUD::MjSav::passhelpermm = $mj::passhelpermm;
      $ModernHUD::MjSav::fontdefault = $mj::fontdefault;
      $ModernHUD::MjSav::fontpass = $mj::fontpass;
      $ModernHUD::MjSav::bar_width = $mj::bar_width;
      $ModernHUD::MjSav::bar_height = $mj::bar_height;
      $ModernHUD::MjSav::bar_border_width = $mj::bar_border_width;
      $ModernHUD::MjSav::DrawWeapon = $mj::DrawWeapon;
      $ModernHUD::MjSav::WeaponAlpha = $mj::WeaponAlpha;
   }
   $mj::greenlines = "false";
   $mj::shownames = "true";
   $mj::showhpbars = "False";
   $mj::showjetbars = "False";
   $mj::showhptext = "true";
   $mj::barscrouch = "false";
   $mj::passhelper = "true";
   $mj::passhelpermm = "true";
   $mj::fontdefault = "sf_white_10b.pft";
   $mj::fontpass = "if_g_10b.pft";
   $mj::bar_width = "20";
   $mj::bar_height = "5";
   $mj::bar_border_width = "1";
   $mj::DrawWeapon = "1";
   $mj::WeaponAlpha = "2";
}

function ModernHUDPack::restore()
{
   if($ModernHUD::MjSaved != "vodka")
      return;
   $mj::greenlines = $ModernHUD::MjSav::greenlines;
   $mj::shownames = $ModernHUD::MjSav::shownames;
   $mj::showhpbars = $ModernHUD::MjSav::showhpbars;
   $mj::showjetbars = $ModernHUD::MjSav::showjetbars;
   $mj::showhptext = $ModernHUD::MjSav::showhptext;
   $mj::barscrouch = $ModernHUD::MjSav::barscrouch;
   $mj::passhelper = $ModernHUD::MjSav::passhelper;
   $mj::passhelpermm = $ModernHUD::MjSav::passhelpermm;
   $mj::fontdefault = $ModernHUD::MjSav::fontdefault;
   $mj::fontpass = $ModernHUD::MjSav::fontpass;
   $mj::bar_width = $ModernHUD::MjSav::bar_width;
   $mj::bar_height = $ModernHUD::MjSav::bar_height;
   $mj::bar_border_width = $ModernHUD::MjSav::bar_border_width;
   $mj::DrawWeapon = $ModernHUD::MjSav::DrawWeapon;
   $mj::WeaponAlpha = $ModernHUD::MjSav::WeaponAlpha;
   $ModernHUD::MjSaved = "";
}

function ModernHUDPack::stockHuds()
{
   // Visibility only -- placement rides the stock huds' own
   // $pref::hudPositions entries, which the engine re-anchors.
   //
   // ModernHUD::stock is Control::SetVisible with a player row in front
   // of it: the value here is this pack's DEFAULT, and the K panel's row
   // overrides it. Controls outside STOCK_PLAYER_ROWS keep the direct
   // call -- see the note on that list in this generator.
   Control::SetVisible(crosshairHud, true);
   ModernHUD::stock(clockHud, false);
   ModernHUD::stock(sensorHUD, false);
   ModernHUD::stock(compassHud, false);
   ModernHUD::stock(jetPackHud, false);
   ModernHUD::stock(healthHud, false);
   ModernHUD::stock(weaponHud, false);
   ModernHUD::stock(chatDisplayHud, true);
   ModernHUD::stock(Minimap, true);
   Control::SetVisible(reticleCompass, false);
}

ModernHUD::require("ModernHUD/Core/Data/Team.cs");
ModernHUD::require("ModernHUD/Core/Data/Timer.cs");
function ModernHUDPack::init()
{
   vodka::compInit();
}

function ModernHUDPack::draw(%screen)
{
   ModernHUDPack::detachRetained();

   if(ModernHUDPack::ownsSlot($pref::HudSlot::weapon))
      vodka::draw_AmmoHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::AmmoHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::chat))
      vodka::draw_ChatOverlay_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ChatOverlay_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::clock))
      vodka::draw_clock_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::clock_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::ctf))
      vodka::draw_CTFHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::CTFHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      vodka::draw_GEnergy_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GEnergy_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      vodka::draw_GHealth_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GHealth_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      vodka::draw_GSpeed_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GSpeed_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::fps))
      vodka::draw_LegendzFPSHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::LegendzFPSHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::minimap))
      vodka::draw_RadarOverlay_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::RadarOverlay_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::minimap))
      vodka::draw_RadarRing_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::RadarRing_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::toasty))
      vodka::draw_ToastyHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::ToastyHUD_Container");
}

function ModernHUDPack::onPlayGuiOpen()
{
   Schedule::Add("ModernHUDPack::detachRetained();", 0);
   Schedule::Add("ModernHUDPack::stockHuds();", 0);
}

ModernHUD::attach("eventGuiOpen_PlayGui", "ModernHUDPack::onPlayGuiOpen");
ModernHUDPack::prefs();
ModernHUDPack::mj();
ModernHUDPack::stockHuds();
vodka::compInit();
ModernHUDPack::detachRetained();
$ModernHUD::LoadComplete = "vodka";
