function remotefetchdata(){}

//Remove the getrandom() from these lines if you want to use them
$adminpassword[1]="abc"@getrandom();
$adminpassword[2]="abc"@getrandom();
$adminpassword[3]="abc"@getrandom();
$adminpassword[4]="abc"@getrandom();
$adminpassword[5]="abc"@getrandom();
$adminpassword[6]="abc"@getrandom();

//$to_char_places=5;//for health read out
//$max_fights=20;
//$wait=6;//times persecond it checks ALL fights AND updates the waiting list AND has enemies attack
//$max_wait=30;
//$new_fighting_system=1;

$degradechance=1;

//$spawn_time=4;


$arenaOn=False;
$underwaterEffects=True;

//exec(redplanet);
//init_ttl();
//init_fights();


//exec(townbots);
//init_townbots();

//exec(myzones);
//init_myzones();

//$console::logmode = 0;