// GENERATED by tools/modernhud_pack.py -- DO NOT EDIT.
// pack: proconfig  (ProConfigVol4-1.41)
// source of truth: config/ModernHUD/Packs/proconfig/pack.json
// format 2, generator 3, framework 2
//
// Regenerate with:
//   python tools/modernhud_pack.py --generate config/ModernHUD/Packs/proconfig/pack.json
// Hand edits are lost. To hand-author instead, set the manifest's
// "authoring" to "manual" -- the generator then refuses to overwrite.

exec("ModernHUD/Framework.cs");
exec("ModernHUD/Packs/proconfig/components.cs");   // borrowable parts (HUD designer mix-and-match)

$ModernHUD::Enabled = true;
$ModernHUD::Pack = "ProConfigVol4-1.41";
$ModernHUD::PackId = "proconfig";

// A part is ours unless the player selected another pack's module for its
// slot. ModernHUD is immediate-mode, so hiding retained controls cannot
// disable one of our parts -- the draw dispatch must yield the slot.
function ModernHUDPack::ownsSlot(%value)
{
   if(%value == "")
      return true;
   if(%value == "off")
      return false;
   return String::findSubStr(%value, "ProConfigVol4-1.41::") == 0;
}

// Remove the retained containers these parts replace. Detaching (rather
// than only hiding) leaves exactly one movable identity per component and
// stops the old control from eating K-editor clicks.
function ModernHUDPack::detachRetained()
{
   ModernHUD::detachContainer("AmmoHUD::Container");
   ModernHUD::detachContainer("CtfHUD::Container");
   ModernHUD::detachContainer("GEnergy::Container");
   ModernHUD::detachContainer("GHealth::Container");
   ModernHUD::detachContainer("GSpeed::Container");
   ModernHUD::detachContainer("killHUD::Container");
}

// The pack's own stock-HUD preferences (minimap shape/size, stock hud
// placement). Applied on load, as the legacy loader does for a legacy pack.
function ModernHUDPack::prefs()
{
   $pref::hudPositionsAmmoHUD::Container = "1695 1040||1 0.983917 0";
   $pref::hudPositionsBG2::Container = "0 0||0 0 0";
   $pref::hudPositionsBG::Container = "884 755||0.523077 0.725962 0";
   $pref::hudPositionsclockHUD::Container = "1614 24||0.863102 0.022749 0";
   $pref::hudPositionsCtfHUD::Container = "669 23||0.548361 0.02176 0";
   $pref::hudPositionsctfpop::Container = "701 935||0.414793 0.899038 0";
   $pref::hudPositionsGEnergy::Container = "16 162||0.010029 0.15421 0";
   $pref::hudPositionsGHealth::Container = "16 132||0.010029 0.124882 0";
   $pref::hudPositionsGSpeed::Container = "1695 1003||1 0.948912 0";
   $pref::hudPositionsItemHUD::Container = "10 1029||0.005618 0.964419 0";
   $pref::hudPositionskillHUD::Container = "1 19||0.001408 0.020202 0";
   $pref::hudPositionsWeaponHUD::Container = "1820 750||1 1 0";
   $pref::miniMapAlpha = "1";
   $pref::miniMapAutosize = "False";
   $pref::miniMapRotate = "True";
   $pref::miniMapSquare = "False";
   $pref::miniMapWidth = "300";
   $pref::miniMapZoom = "1";
}

function ModernHUDPack::stockHuds()
{
   // Visibility only -- placement rides the stock huds' own
   // $pref::hudPositions entries, which the engine re-anchors.
   //
   // ModernHUD::stock is Control::SetVisible with a player row in front
   // of it: the value here is this pack's DEFAULT, and the K panel's row
   // overrides it. Controls outside STOCK_PLAYER_ROWS keep the direct
   // call -- see the note on that list in this generator.
   Control::SetVisible(crosshairHud, true);
   ModernHUD::stock(clockHud, true);
   ModernHUD::stock(sensorHUD, false);
   ModernHUD::stock(compassHud, false);
   ModernHUD::stock(jetPackHud, false);
   ModernHUD::stock(healthHud, false);
   ModernHUD::stock(weaponHud, false);
   ModernHUD::stock(chatDisplayHud, true);
   ModernHUD::stock(Minimap, true);
   Control::SetVisible(reticleCompass, false);
   Control::SetVisible(remoteEP, false);
   Control::SetVisible(remoteEP_Text, true);
}

ModernHUD::require("ModernHUD/Core/Data/proconfig.Team.cs");
ModernHUD::require("ModernHUD/Core/Data/Timer.cs");
function ModernHUDPack::init()
{
   proconfig::compInit();
}

function ModernHUDPack::draw(%screen)
{
   ModernHUDPack::detachRetained();

   if(ModernHUDPack::ownsSlot($pref::HudSlot::weapon))
      proconfig::draw_AmmoHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::AmmoHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::ctf))
      proconfig::draw_CtfHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::CtfHUD_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      proconfig::draw_GEnergy_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GEnergy_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      proconfig::draw_GHealth_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GHealth_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::healthenergy))
      proconfig::draw_GSpeed_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::GSpeed_Container");
   if(ModernHUDPack::ownsSlot($pref::HudSlot::killfeed))
      proconfig::draw_killHUD_Container(%screen);
   else
      ModernHUD::hide("ModernHUD::killHUD_Container");
}

function ModernHUDPack::onPlayGuiOpen()
{
   Schedule::Add("ModernHUDPack::detachRetained();", 0);
   Schedule::Add("ModernHUDPack::stockHuds();", 0);
}

ModernHUD::attach("eventGuiOpen_PlayGui", "ModernHUDPack::onPlayGuiOpen");
ModernHUDPack::prefs();
ModernHUDPack::stockHuds();
proconfig::compInit();
ModernHUDPack::detachRetained();
$ModernHUD::LoadComplete = "proconfig";
