$MDESC::Creator = "Capture the Flag";
$MDESC::Planet = "Omicron Argentis VI";
$MDESC::TeamCount = "2";
$MDESC::TimeOfDay = "Night";
$MDESC::Weather = "Clear";
$MDESC::Type = "Capture the Flag Air";
$MDESC::Text = "\n<s3>\n<f1>Mission Type : <f0>Capture the Flag\n<f1>Planet : <f0>Omicron Argentis VI\n<f1>Weather : <f0>Clear\n<f1>Time of Day : <f0>Night\n<f1># of Teams : <f0>2\n<f1>Briefing : <f0>The <vServer::teamName0> and <vServer::teamName1> battle each other for there flags. Both the <vServer::teamName0> and <vServer::teamName1> lack a flag base but they have stored there flags in a heavily guarded area. Make sure to use the sniper bunkers    \n\n<f1>Map Creator : <f0>{-o-} Coal\n<f1>E-mail : <f0>ElementOfOne@aol.com\n<f1>Special Thanks to : <f0>{-o-} TartLoaf\n<f1>DV :V2.0.16";
$cdTrack = ;;
$cdPlaymode = ;;
