$MDESC::Creator = "{-o-} Coal";
$MDESC::Planet = "Deus Sanguinius";
$MDESC::TeamCount = "2";
$MDESC::TimeOfDay = "Midday";
$MDESC::Weather = "Clear";
$MDESC::Type = "Capture the Flag Air";
$MDESC::Text = "\n<s3>\n<f1>Mission Type : <f0>Capture the Flag\n<f1>Planet : <f0>Deus Sanguinius\n<f1>Weather : <f0>Clear\n<f1>Time of Day : <f0>Midday\n<f1># of Teams : <f0>2\n<f1>Briefing : <f0>The <vServer::teamName0> and <vServer::teamName1> battle each other from close range on there flag bases. Both teams have defended the flags well against attack. The only way to gain access to the flag is to fly in on the open platform at the front of bas \n\n<f1>Map Creator : <f0>{-o-} Coal\n<f1>E-mail : <f0>ElementOfOne@aol.com\n<f1>DV :V2.0.16";
$cdTrack = ;
$cdPlaymode = ;
