$Server::HostName = "RPG v6.7"; // Server name
$Server::Password = ""; // Want your server passworded? Stick it in between the quotes
$Server::JoinPassword = ""; // Does nothing..
$Server::MaxPlayers = "7"; // Maximum players you want on your server?
$pref::LastMission = "rpgmap6"; // rpgmap1, rpgmap5, and rpgmap6 come with RPG mod. 1 won't work properly, 6 has new shapes.
$AdminPassword[1] = "";
$AdminPassword[2] = "";
$AdminPassword[3] = "";
$AdminPassword[4] = "";
$AdminPassword[5] = "";//Fill them all in for passwords to work, don't use just numbers
//$SanctionedAdmin["phantom"] = 1;//Example for better admin setup.
$loginmsg = "<f0>Welcome to my Tribes RPG server!\n<f1>Admin: <f2>YOUR NAME HERE\n<f0>Have fun!"; // This message comes to a new player on his/her first spawn
$Server::Port = "28001"; // Best to not touch if you don't know what it is
$Server::HostPublicGame = "true"; // Let other people see your server?
$Server::FloodProtectionEnabled = "false"; // Extra chat flood protection?
$arenaOn = "true"; // true for arena, false for no arena
$underwaterEffects = "false"; // Neat feature.. You'll see... If you set it to true.
$postAttackGraphBar = "false"; // Probably shouldn't use anymore
$AIsmartFOVbots = "false"; // I usually don't touch this..
$SelectiveZoneBotSpawning = "true"; // Spawn bots only if players are near?
$displayPingAndPL = "false"; // False for showing class in tab menu
$allowDuplicateIPs = "true"; // Allow more than one player per IP?
$initlck = "20"; // Amount of LCK a new person starts with
$maxPets = "5"; // Max helper bots in server
$maxPetsPerPlayer = "1"; // Max helper bots per player
$maxSAYdistVec = "20"; // Max say distance
$maxSHOUTdistVec = "60"; // Max shout distance
$SPgainedPerLevel = "25"; // SP gained per level
$initSPcredits = "30"; // How much SP do you want them to start with?
$autoStartupSP = "10"; // SP per skill at start
$initbankcoins = "50"; // How many coins in a new player's bank?
$SaveWorldFreq = "300"; // 300 is 5 minutes, this goes by seconds
$recallDelay = "300"; // 300 is 5 minutes, this goes by seconds
$spawnMultiplier = "1.0"; // I usually don't touch this..
$console::logmode = 1; // 0 if no and 1 if yes; logs console output to console.log
$extrainfo = "";//Extra server info goes here (info seen outside game in lobby, and in game on escape screen)
