
//football missions only
exec(missionlist);
MissionList::clear();
Missionlist::initNextMission();
$pref::lastmission = "Hoops";
MissionList::addMission("TunnelBall");
MissionList::addMission("TK-421_Stadium");
MissionList::addMission("Tech_Ball");
MissionList::addMission("SpaceStation_Stadium");
MissionList::addMission("SpaceBall");
MissionList::addMission("Snowball_Express2");
MissionList::addMission("Snowball_Express");
MissionList::addMission("SlamDunk_Stadium");
MissionList::addMission("Shooters_Stadium");
MissionList::addMission("RomanFootBall");
MissionList::addMission("RamppedTouchdown");
MissionList::addMission("PrisonCamp");
MissionList::addMission("PikaDropStadium");
MissionList::addMission("Official_Stadium9");
MissionList::addMission("Official_Stadium8");
MissionList::addMission("Official_Stadium7");
MissionList::addMission("Official_Stadium6");
MissionList::addMission("Official_Stadium5");
MissionList::addMission("Official_Stadium4");
MissionList::addMission("Official_Stadium3");
MissionList::addMission("Official_Stadium2");
MissionList::addMission("Official_Stadium1");
MissionList::addMission("NoFear_Stadium");
MissionList::addMission("MudBowlMX");
MissionList::addMission("MudBowl");
MissionList::addMission("MoonJump_Stadium");
MissionList::addMission("MontyCrisco_Stadium");
MissionList::addMission("Midnight_Run");
MissionList::addMission("Longest_Yard");
MissionList::addMission("LN2_Stadium");
MissionList::addMission("Kings_Stadium");
MissionList::addMission("InDoorsArena");
MissionList::addMission("IceBall");
MissionList::addMission("HoopsMX");
MissionList::addMission("Hoops");
MissionList::addMission("HolyMoly_Stadium");
MissionList::addMission("HighSchool");
MissionList::addMission("Highjump_Stadium");
MissionList::addMission("HighEndzone");
MissionList::addMission("HalfpipeMX_Stadium");
MissionList::addMission("Halfpipe_Stadium");
MissionList::addMission("Ghostrider_Stadium");
MissionList::addMission("Frisbee_ConversionA");
MissionList::addMission("Fortress_Stadium");
MissionList::addMission("football");
MissionList::addMission("FlyingNights_Stadium");
MissionList::addMission("FlyingKnightsMX_Stadium");
MissionList::addMission("FlyBall");
MissionList::addMission("Extreme_Stadium");
MissionList::addMission("EEPROM_Stadium");
MissionList::addMission("DesertHigh_StadiumMX");
MissionList::addMission("DesertHigh_Stadium");
MissionList::addMission("DesertBowl");
MissionList::addMission("Cyclone_Stadium");
MissionList::addMission("Cavern_Stadium");
MissionList::addMission("BlueBalls_Stadium");
$nextMission["football"] = "RamppedTouchdown";
$nextMission["RamppedTouchdown"] = "Official_Stadium1";
$nextMission["Official_Stadium1"] = "Official_Stadium2";
$nextMission["Official_Stadium2"] = "Official_Stadium3";
$nextMission["Official_Stadium3"] = "Official_Stadium4";
$nextMission["Official_Stadium4"] = "Official_Stadium5";
$nextMission["Official_Stadium5"] = "Official_Stadium6";
$nextMission["Official_Stadium6"] = "Official_Stadium7";
$nextMission["Official_Stadium7"] = "Official_Stadium8";
$nextMission["Official_Stadium8"] = "Official_Stadium9";
$nextMission["Official_Stadium9"] = "Snowball_Express2";
$nextMission["Snowball_Express2"] = "DesertHigh_Stadium";
$nextMission["DesertHigh_Stadium"] = "EEPROM_Stadium";
$nextMission["EEPROM_Stadium"] = "DesertHigh_StadiumMX";
$nextMission["DesertHigh_StadiumMX"] = "Halfpipe_Stadium";
$nextMission["Halfpipe_Stadium"] = "Hoops";
$nextMission["Hoops"] = "BlueBalls_Stadium";
$nextMission["BlueBalls_Stadium"] = "RomanFootBall";
$nextMission["RomanFootBall"] = "TunnelBall";
$nextMission["TunnelBall"] = "TK-421_Stadium";
$nextMission["TK-421_Stadium"] = "Tech_Ball";
$nextMission["Tech_Ball"] = "FlyingNights_Stadium";
$nextMission["FlyingNights_Stadium"] = "Cyclone_Stadium";
$nextMission["Cyclone_Stadium"] = "MontyCrisco_Stadium";
$nextMission["MontyCrisco_Stadium"] = "Kings_Stadium";
$nextMission["Kings_Stadium"] = "SlamDunk_Stadium";
$nextMission["SlamDunk_Stadium"] = "NoFear_Stadium";
$nextMission["NoFear_Stadium"] = "Ghostrider_Stadium";
$nextMission["Ghostrider_Stadium"] = "Geometric_Stadium";
$nextMission["Geometric_Stadium"] = "FlyingKnightsMX_Stadium";
$nextMission["FlyingKnightsMX_Stadium"] = "Extreme_Stadium";
$nextMission["Extreme_Stadium"] = "HalfpipeMX_Stadium";
$nextMission["HalfpipeMX_Stadium"] = "HoopsMX";
$nextMission["HoopsMX"] = "Shooters_Stadium";
$nextMission["Shooters_Stadium"] = "Longest_Yard";
$nextMission["Longest_Yard"] = "Midnight_Run";
$nextMission["Midnight_Run"] = "MudBowl";
$nextMission["MudBowl"] = "LN2_Stadium";
$nextMission["LN2_Stadium"] = "MoonJump_Stadium";
$nextMission["MoonJump_Stadium"] = "Frisbee_ConversionA";
$nextMission["Frisbee_ConversionA"] = "HolyMoly_Stadium";
$nextMission["HolyMoly_Stadium"] = "MudBowlMX";
$nextMission["MudBowlMX"] = "SpaceStation_Stadium";
$nextMission["SpaceStation_Stadium"] = "Highjump_Stadium";
$nextMission["Highjump_Stadium"] = "DesertBowl";
$nextMission["DesertBowl"] = "FlyBall";
$nextMission["FlyBall"] = "Fortress_Stadium";
$nextMission["Fortress_Stadium"] = "HighEndzone";
$nextMission["HighEndzone"] = "HighSchool";
$nextMission["HighSchool"] = "IceBall";
$nextMission["IceBall"] = "InDoorsArena";
$nextMission["InDoorsArena"] = "PrisonCamp";
$nextMission["PrisonCamp"] = "SpaceBall";
$nextMission["SpaceBall"] = "football";
