// Generated by the mission editor's model browser. These StaticShapeData
// blocks back the .dts models placed in this map, and MUST load before the
// .mis that names them -- Server::finishMissionLoad execs this file first.
// Ship it with the map; captureMission() bundles it.

StaticShapeData MEShape_anten_lrg
{
   description = "anten_lrg";
   shapeFile = "anten_lrg";
   shadowDetailLevel = 0;
   maxDamage = 5.0;
};

$ME::shapesLoaded = "MEShape_anten_lrg";
