//--------------------------------------------------------------------------
// HercCabasl -- Starsiege Herc as a Tribes armor.
//
// Generated by tools/starsiege_to_tribes.py.
// A Herc walks because Tribes players pick their animation from measured
// root motion; vehicles never animate. See the tool docstring.
//
// The shape has had the Tribes player utility nodes injected
// (tools/inject_player_nodes.py): "dummyalways root",
// "dummyalways chasecam", and per detail size "dummy hand<N>",
// "dummy unused<N>", "dummy midback<N>", "dummy lowback<N>",
// "dummy eye<N>" -- the names Player::initResources resolves.
//
// Collision box + chase-camera height are sized to the model's
// measured bind-pose extents (a Herc is ~7m tall vs a trooper ~2m).
// Skins are 24-bit true-color BMP so the engine does not recolor them
// through its world palette. Install with the tool's --install step.
//--------------------------------------------------------------------------

PlayerData HercCabasl
{
   className = "Armor";
   shapeFile = "ca_basl";
   //  no damage skins / flame / shield shapes: those are Tribes-player
   //  assets and a Herc has none. Leaving them unset is safe.
   validateShape = false;

   visibleToSensor = true;
   mapFilter = 1;
   mapIcon = "M_player";
   canCrouch = true;

   // Scaled up from a Tribes trooper: the shape is ~10.8m in radius.
   maxDamage = 4.0;
   maxForwardSpeed = 6;
   maxBackwardSpeed = 4;
   maxSideSpeed = 4;
   groundForce = 40 * 30.0;
   mass = 60.0;
   groundTraction = 3.0;
   maxEnergy = 100;
   drag = 1.0;
   density = 1.2;

   minDamageSpeed = 40;
   damageScale = 0.002;
   jumpImpulse = 0;      // Hercs do not jump
   jumpSurfaceMinDot = 0.2;
   minJetEnergy = 1;
   jetForce = 0;         // and do not jet
   jetEnergyDrain = 0;

   // collision hull sized to the model (measured extents:
   //   halfW 4.06  halfD 6.65  height 9.13)
   boxWidth = 4.06;
   boxDepth = 6.65;
   boxNormalHeight = 9.13;
   boxCrouchHeight = 6.39;
   boxNormalHeadPercentage  = 0.83;
   boxNormalTorsoPercentage = 0.53;
   boxCrouchHeadPercentage  = 0.6666;
   boxCrouchTorsoPercentage = 0.3333;
   boxHeadLeftPercentage  = 0;
   boxHeadRightPercentage = 1;
   boxHeadBackPercentage  = 0;
   boxHeadFrontPercentage = 1;

   // animation name, sound, direction, firstPerson, chaseCam,
   // thirdPerson, signalThread, priority
   animData[0] = { "root", none, 1, true, true, true, false, 0 };
   animData[1] = { "run", none, 1, true, true, true, false, 3 };
   animData[2] = { "run", none, -1, true, true, true, false, 3 };
   animData[3] = { "run", none, 1, true, true, true, false, 3 };
   animData[4] = { "run", none, -1, true, true, true, false, 3 };
   animData[5] = { "root", none, 1, true, true, true, false, 3 };
   animData[6] = { "run", none, 1, true, true, true, false, 3 };
   animData[7] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[8] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[9] = { "crouch root", none, -1, true, true, true, false, 3 };
   animData[10] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[11] = { "crouch root", none, -1, true, true, true, false, 3 };
   animData[12] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[13] = { "crouch root", none, -1, true, true, true, false, 3 };
   animData[14] = { "fall", none, 1, true, true, true, false, 3 };
   animData[15] = { "landing", none, 1, true, true, true, false, 3 };
   animData[16] = { "landing", none, 1, true, true, true, false, 3 };
   animData[17] = { "fall", none, 1, true, true, true, false, 3 };
   animData[18] = { "landing", none, 1, true, true, true, false, 3 };
   animData[19] = { "fall", none, 1, true, true, true, false, 3 };
   animData[20] = { "root", none, 1, true, true, true, false, 3 };
   animData[21] = { "root", none, 1, true, true, true, false, 3 };
   animData[22] = { "root", none, 1, true, true, true, false, 3 };
   animData[23] = { "root", none, 1, true, true, true, false, 3 };
   animData[24] = { "root", none, 1, true, true, true, false, 3 };
   animData[25] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[26] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[27] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[28] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[29] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[30] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[31] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[32] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[33] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[34] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[35] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[36] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[37] = { "crouch root", none, 1, true, true, true, false, 3 };
   animData[38] = { "root", none, 1, true, true, true, false, 3 };
   animData[39] = { "root", none, 1, true, true, true, false, 3 };
   animData[40] = { "root", none, 1, true, true, true, false, 3 };
   animData[41] = { "root", none, 1, true, true, true, false, 3 };
   animData[42] = { "root", none, 1, true, true, true, false, 3 };
   animData[43] = { "root", none, 1, true, true, true, false, 3 };
   animData[44] = { "root", none, 1, true, true, true, false, 3 };
   animData[45] = { "root", none, 1, true, true, true, false, 3 };
   animData[46] = { "root", none, 1, true, true, true, false, 3 };
   animData[47] = { "root", none, 1, true, true, true, false, 3 };
   animData[48] = { "root", none, 1, true, true, true, false, 3 };
   animData[49] = { "root", none, 1, true, true, true, false, 3 };
   animData[50] = { "root", none, 1, true, true, true, false, 3 };
};


//--- wear it -----------------------------------------------------------
// IMPORTANT: this datablock must be declared at SERVER STARTUP, not from
// the console. createServer() (base scripts.vol server.cs) execs the
// armor/item/etc. files and THEN calls preloadServerDataBlocks(); a
// PlayerData declared after that is never registered, so Player::setArmor
// silently reverts (verified: a console-exec'd datablock on the stock
// larmor shape fails while startup-declared larmor works).
//
// The tool's --install step makes a loose base\armordata.cs (stock copy +
// exec("herccabasl.cs")), which createServer runs before preload. After
// installing, RESTART the listen server, then:
//
//     beHercCabasl();
//
// On a listen server the console is the server console, so Player::setArmor
// works directly -- $ServerCheats only gates the remoteSetArmor path that
// remote clients use.
//
// Spawn in as a normal player FIRST -- there has to be a control object to
// re-skin. GameBase::setDatFileName reloads the datablock and reverts to
// the previous one if the new shape fails to load, so a bad port is not
// fatal -- watch the console for the revert.

// Find the SERVER-side player object.
//
// Player::setArmor resolves its argument with findPlayerObject(), which
// searches the SERVER manager (sg.manager, FearPlugin.cpp:219).
// getLocalObject() returns the CLIENT PSC's control object -- a ghost with
// a different id -- so passing it yields a non-zero id that findPlayerObject
// still cannot resolve, and setArmor/getArmor just answer "False".
// Client::getControlObject(id) goes through sg.playerManager and returns the
// real server object, so scan the client ids. They start at 2048, not 0
// (PlayerManager: clientId = readInt(7) + 2048); a listen host is 2048.
function findServerPlayer()
{
   for (%i = 2048; %i < 2176; %i++) {
      %o = Client::getControlObject(%i);
      if (%o > 0 && Player::getClient(%o) > 0)
         return %o;
   }
   return -1;
}

function beHercCabasl()
{
   %p = findServerPlayer();
   if (%p <= 0) {
      echo("beHercCabasl: no server-side player found -- spawn into the world first.");
      echo("  (getLocalObject() = " @ getLocalObject() @ " is the client ghost, not usable here)");
      return;
   }
   echo("player object " @ %p @ " (client " @ Player::getClient(%p) @ "), armor was " @ Player::getArmor(%p));
   Player::setArmor(%p, "HercCabasl");
   echo("armor is now: " @ Player::getArmor(%p));
}

// back to a stock trooper
function beHercCabasl_off()
{
   %p = findServerPlayer();
   if (%p > 0) {
      Player::setArmor(%p, "larmor");
      echo("armor is now: " @ Player::getArmor(%p));
   }
}
