// MechArmorData.cs -- Starsiege Herc armors for Tribes.
// Generated by tools/build_herc_pack.py. Do not hand-edit; re-run the tool.
//
// ★Exec'd ONLY when the host sets $MechPack::Enable = 1.★  Every datablock a
// server registers is sent to every client, and a client missing the matching
// .dts is DISCONNECTED with "The server has new art data you are missing"
// (dataBlockManager.cpp:436, shapeBase.cpp:146). Registering these
// unconditionally would lock stock clients out of any server that merely has
// the pack installed, so this stays opt-in and old clients keep working.
//
// To use the mechs on a server you host:
//     $MechPack::Enable = 1;      (in config, BEFORE createServer)
// then in game:  beHercKntalon();  etc.
//
// Every connecting client then needs this pack too.

exec("herccabasl.cs");
exec("herccinapoc.cs");
exec("herccinbasl.cs");
exec("herccyexec.cs");
exec("herccygoad.cs");
exec("herccyjudg.cs");
exec("herccyprom.cs");
exec("herccyseek.cs");
exec("herccyshep.cs");
exec("herchaapoc.cs");
exec("hercknapoc.cs");
exec("hercknbasl.cs");
exec("herckngorg.cs");
exec("hercknmino.cs");
exec("herckntalon.cs");
exec("hercmgexec.cs");
exec("hercmggoad.cs");
exec("hercmgjudg.cs");
exec("hercmgseek.cs");
exec("hercmgshep.cs");
exec("hercpiapoc.cs");
exec("hercpieman.cs");
exec("hercplexec.cs");
exec("hercpljudg.cs");
exec("hercrbeman.cs");
exec("hercrboly.cs");
exec("herctrapoc.cs");
exec("herctrbasl.cs");
exec("herctrgorg.cs");
exec("herctrmino.cs");
exec("herctrtalon.cs");
