//----------------------------------------------------------------------------
// Mech Mayhem -- FULL authentic Starsiege arsenal.
// GENERATED by tools/mech_weapon_gen.py from starsiege_weapons_full.json --
// do not hand-edit; re-run the tool. Stats are the real Starsiege projectile
// tables normalized to mod scale (see the generator header for the math).
// All weapons reactor-fed (energy = heat), matching the heat-governor design.
//----------------------------------------------------------------------------

//--- Starsiege impact/explosion effects (shapes extracted from
//--- gameobjects.vol by tools/mech_fx_extract.py; the engine loads the
//--- v7 .dts natively) ------------------------------------------------------

ExplosionData MechImpSm
{
   shapeName = "fx_imp_sm.dts";
   soundId   = ricochet1;
   faceCamera = true;
   randomSpin = false;
   hasLight   = false;
   lightRange = 0.0;
   timeScale  = 1.0;
   timeZero   = 0.250;
   timeOne    = 0.850;
   colors[0]  = { 0.8, 0.7, 0.5 };
   colors[1]  = { 0.8, 0.7, 0.5 };
   colors[2]  = { 0.0, 0.0, 0.0 };
   radFactors = { 0.5, 1.0, 1.0 };
};

ExplosionData MechImpMd
{
   shapeName = "fx_imp_md.dts";
   soundId   = ricochet2;
   faceCamera = true;
   randomSpin = false;
   hasLight   = false;
   lightRange = 0.0;
   timeScale  = 1.0;
   timeZero   = 0.250;
   timeOne    = 0.850;
   colors[0]  = { 0.8, 0.7, 0.5 };
   colors[1]  = { 0.8, 0.7, 0.5 };
   colors[2]  = { 0.0, 0.0, 0.0 };
   radFactors = { 0.5, 1.0, 1.0 };
};

ExplosionData MechImpTn
{
   shapeName = "fx_imp_tn.dts";
   soundId   = energyExplosion;
   faceCamera = true;
   randomSpin = false;
   hasLight   = true;
   lightRange = 3.0;
   timeScale  = 1.0;
   timeZero   = 0.250;
   timeOne    = 0.850;
   colors[0]  = { 0.5, 0.7, 1.0 };
   colors[1]  = { 0.5, 0.7, 1.0 };
   colors[2]  = { 0.0, 0.0, 0.0 };
   radFactors = { 0.5, 1.0, 1.0 };
};

ExplosionData MechImpFb
{
   shapeName = "fx_imp_fb.dts";
   soundId   = energyExplosion;
   faceCamera = true;
   randomSpin = false;
   hasLight   = true;
   lightRange = 3.0;
   timeScale  = 1.0;
   timeZero   = 0.250;
   timeOne    = 0.850;
   colors[0]  = { 1.0, 0.6, 0.3 };
   colors[1]  = { 1.0, 0.6, 0.3 };
   colors[2]  = { 0.0, 0.0, 0.0 };
   radFactors = { 0.5, 1.0, 1.0 };
};

ExplosionData MechImpSp
{
   shapeName = "fx_imp_sp.dts";
   soundId   = shockExplosion;
   faceCamera = true;
   randomSpin = false;
   hasLight   = true;
   lightRange = 3.0;
   timeScale  = 1.0;
   timeZero   = 0.250;
   timeOne    = 0.850;
   colors[0]  = { 0.7, 0.5, 1.0 };
   colors[1]  = { 0.7, 0.5, 1.0 };
   colors[2]  = { 0.0, 0.0, 0.0 };
   radFactors = { 0.5, 1.0, 1.0 };
};

ExplosionData MechExpSm
{
   shapeName = "fx_exp_sm.dts";
   soundId   = explosion4;
   faceCamera = true;
   randomSpin = false;
   hasLight   = true;
   lightRange = 5.0;
   timeScale  = 1.0;
   timeZero   = 0.250;
   timeOne    = 0.850;
   colors[0]  = { 1.0, 0.7, 0.3 };
   colors[1]  = { 1.0, 0.7, 0.3 };
   colors[2]  = { 0.0, 0.0, 0.0 };
   radFactors = { 0.5, 1.0, 1.0 };
};

ExplosionData MechExpMd
{
   shapeName = "fx_exp_md.dts";
   soundId   = rocketExplosion;
   faceCamera = true;
   randomSpin = false;
   hasLight   = true;
   lightRange = 8.0;
   timeScale  = 1.0;
   timeZero   = 0.250;
   timeOne    = 0.850;
   colors[0]  = { 1.0, 0.7, 0.3 };
   colors[1]  = { 1.0, 0.7, 0.3 };
   colors[2]  = { 0.0, 0.0, 0.0 };
   radFactors = { 0.5, 1.0, 1.0 };
};

ExplosionData MechExpLg
{
   shapeName = "fx_exp_lg.dts";
   soundId   = bigExplosion3;
   faceCamera = true;
   randomSpin = false;
   hasLight   = true;
   lightRange = 12.0;
   timeScale  = 1.0;
   timeZero   = 0.250;
   timeOne    = 0.850;
   colors[0]  = { 1.0, 0.65, 0.25 };
   colors[1]  = { 1.0, 0.65, 0.25 };
   colors[2]  = { 0.0, 0.0, 0.0 };
   radFactors = { 0.5, 1.0, 1.0 };
};

//--- projectiles ------------------------------------------------------------

LaserData MechLaserShot
{
   laserBitmapName   = "fx_las.bmp";
   hitName           = "fx_imp_tn.dts";
   damageConversion  = 0.0717;
   baseDamageType    = $LaserDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 1.0, 0.3, 0.3 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

LaserData MechHeavyLaserShot
{
   laserBitmapName   = "fx_hlas.bmp";
   hitName           = "fx_imp_tn.dts";
   damageConversion  = 0.0716;
   baseDamageType    = $LaserDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 1.0, 0.3, 0.3 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

LaserData MechCompressionLaserShot
{
   laserBitmapName   = "fx_clas.bmp";
   hitName           = "fx_imp_tn.dts";
   damageConversion  = 0.0716;
   baseDamageType    = $LaserDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 1.0, 0.3, 0.3 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

LaserData MechTwinLaserShot
{
   laserBitmapName   = "fx_tlas.bmp";
   hitName           = "fx_imp_tn.dts";
   damageConversion  = 0.0709;
   baseDamageType    = $LaserDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 1.0, 0.3, 0.3 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

BulletData MechElectroMagneticPulseCannonShot
{
   bulletShapeName    = "pr_emp.dts";
   explosionTag       = MechExpSm;
   damageClass        = 1;
   damageValue        = 0.272;
   damageType         = $BlasterDamageType;
   explosionRadius    = 0.6;
   muzzleVelocity     = 315.0;
   totalTime          = 1.43;
   liveTime           = 1.0;
   lightRange         = 3.0;
   lightColor         = { 0.25, 0.9, 1.0 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

LaserData MechElectronFluxWhipShot
{
   laserBitmapName   = "fx_elf.bmp";
   hitName           = "fx_exp_sm.dts";
   damageConversion  = 0.0715;
   baseDamageType    = $PlasmaDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 0.7, 0.3, 1.0 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

BulletData MechBlasterShot
{
   bulletShapeName    = "pr_blas.dts";
   explosionTag       = MechExpSm;
   damageClass        = 1;
   damageValue        = 0.87;
   damageType         = $BlasterDamageType;
   explosionRadius    = 0.1;
   muzzleVelocity     = 225.0;
   totalTime          = 2.4;
   liveTime           = 1.68;
   lightRange         = 3.0;
   lightColor         = { 0.25, 0.9, 1.0 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

BulletData MechHeavyBlasterShot
{
   bulletShapeName    = "pr_hbla.dts";
   explosionTag       = MechExpSm;
   damageClass        = 1;
   damageValue        = 1.163;
   damageType         = $BlasterDamageType;
   explosionRadius    = 0.1;
   muzzleVelocity     = 191.2;
   totalTime          = 2.35;
   liveTime           = 1.65;
   lightRange         = 3.0;
   lightColor         = { 0.25, 0.9, 1.0 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

LaserData MechParticleBeamWeaponShot
{
   laserBitmapName   = "fx_pbw.bmp";
   hitName           = "fx_imp_tn.dts";
   damageConversion  = 0.0713;
   baseDamageType    = $BlasterDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 0.25, 0.9, 1.0 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

LaserData MechPlasmaShot
{
   laserBitmapName   = "fx_plas.bmp";
   hitName           = "fx_exp_sm.dts";
   damageConversion  = 0.0713;
   baseDamageType    = $PlasmaDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 0.7, 0.3, 1.0 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

BulletData MechBlinkGunShot
{
   bulletShapeName    = "pr_blnk.dts";
   explosionTag       = MechImpTn;
   damageClass        = 0;
   damageValue        = 0.391;
   damageType         = $BlasterDamageType;
   muzzleVelocity     = 315.0;
   totalTime          = 1.43;
   liveTime           = 1.0;
   lightRange         = 3.0;
   lightColor         = { 0.25, 0.9, 1.0 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

LaserData MechQuantumGunShot
{
   laserBitmapName   = "fx_qgun.bmp";
   hitName           = "fx_exp_sm.dts";
   damageConversion  = 0.0716;
   baseDamageType    = $BlasterDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 0.25, 0.9, 1.0 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

BulletData MechMagnetoFusionAssaultCannonShot
{
   bulletShapeName    = "pr_mfac.dts";
   explosionTag       = MechImpMd;
   damageClass        = 1;
   damageValue        = 2.174;
   damageType         = $ExplosionDamageType;
   explosionRadius    = 0.3;
   muzzleVelocity     = 135.0;
   totalTime          = 3.33;
   liveTime           = 2.33;
   lightRange         = 3.0;
   lightColor         = { 1.0, 0.8, 0.3 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

BulletData MechNannoInfuserShot
{
   bulletShapeName    = "pr_nano.dts";
   explosionTag       = MechImpSp;
   damageClass        = 1;
   damageValue        = 0.761;
   damageType         = $ShrapnelDamageType;
   explosionRadius    = 0.6;
   muzzleVelocity     = 166.5;
   totalTime          = 1.08;
   liveTime           = 0.76;
   lightRange         = 3.0;
   lightColor         = { 0.6, 1.0, 0.4 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

LaserData MechNanniteCannonShot
{
   laserBitmapName   = "fx_ncan.bmp";
   hitName           = "fx_exp_sm.dts";
   damageConversion  = 0.0715;
   baseDamageType    = $ShrapnelDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 1.0, 0.4, 0.4 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

BulletData MechAutocannonShot
{
   bulletShapeName    = "pr_atc.dts";
   explosionTag       = MechImpSm;
   damageClass        = 0;
   damageValue        = 0.326;
   damageType         = $BulletDamageType;
   muzzleVelocity     = 225.0;
   totalTime          = 1.3;
   liveTime           = 0.91;
   lightRange         = 3.0;
   lightColor         = { 1.0, 0.8, 0.3 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

BulletData MechHeavyAutocannonShot
{
   bulletShapeName    = "pr_hatc.dts";
   explosionTag       = MechImpSm;
   damageClass        = 0;
   damageValue        = 0.489;
   damageType         = $BulletDamageType;
   muzzleVelocity     = 157.5;
   totalTime          = 1.43;
   liveTime           = 1.0;
   lightRange         = 3.0;
   lightColor         = { 1.0, 0.8, 0.3 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

BulletData MechElectroMagAutocannonShot
{
   bulletShapeName    = "pr_emc.dts";
   explosionTag       = MechImpSm;
   damageClass        = 0;
   damageValue        = 0.38;
   damageType         = $BulletDamageType;
   muzzleVelocity     = 180.0;
   totalTime          = 1.5;
   liveTime           = 1.05;
   lightRange         = 3.0;
   lightColor         = { 1.0, 0.8, 0.3 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

BulletData MechBlastCannonShot
{
   bulletShapeName    = "pr_bc.dts";
   explosionTag       = MechImpMd;
   damageClass        = 1;
   damageValue        = 0.652;
   damageType         = $ExplosionDamageType;
   explosionRadius    = 6.0;
   muzzleVelocity     = 157.5;
   totalTime          = 3.0;
   liveTime           = 2.1;
   lightRange         = 3.0;
   lightColor         = { 1.0, 0.8, 0.3 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

BulletData MechHeavyBlastCannonShot
{
   bulletShapeName    = "pr_hbc.dts";
   explosionTag       = MechExpSm;
   damageClass        = 1;
   damageValue        = 0.87;
   damageType         = $ExplosionDamageType;
   explosionRadius    = 6.0;
   muzzleVelocity     = 135.0;
   totalTime          = 3.0;
   liveTime           = 2.1;
   lightRange         = 3.0;
   lightColor         = { 1.0, 0.8, 0.3 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

BulletData MechRailGunShot
{
   bulletShapeName    = "pr_rail.dts";
   explosionTag       = MechImpMd;
   damageClass        = 1;
   damageValue        = 0.815;
   damageType         = $ExplosionDamageType;
   explosionRadius    = 0.3;
   muzzleVelocity     = 450.0;
   totalTime          = 1.0;
   liveTime           = 0.7;
   lightRange         = 3.0;
   lightColor         = { 1.0, 0.8, 0.3 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

GrenadeData MechLaserGuidedBombShot
{
   bulletShapeName    = "pr_vip.dts";
   explosionTag       = MechExpLg;
   collideWithOwner   = True;
   ownerGraceMS       = 600;
   collisionRadius    = 0.25;
   mass               = 6.0;
   elasticity         = 0.2;
   damageClass        = 1;
   damageValue        = 1.304;
   damageType         = $ExplosionDamageType;
   explosionRadius    = 6.0;
   kickBackStrength   = 300.0;
   maxLevelFlightDist = 220;
   totalTime          = 30.0;
   liveTime           = 1.5;
   projSpecialTime    = 0.05;
   inheritedVelocityScale = 0.5;
   smokeName          = "smoke.dts";
};

GrenadeData MechHadesShot
{
   bulletShapeName    = "pr_vip.dts";
   explosionTag       = MechExpLg;
   collideWithOwner   = True;
   ownerGraceMS       = 600;
   collisionRadius    = 0.25;
   mass               = 6.0;
   elasticity         = 0.2;
   damageClass        = 1;
   damageValue        = 1.087;
   damageType         = $LaserDamageType;
   explosionRadius    = 9.0;
   kickBackStrength   = 300.0;
   maxLevelFlightDist = 220;
   totalTime          = 30.0;
   liveTime           = 1.5;
   projSpecialTime    = 0.05;
   inheritedVelocityScale = 0.5;
   smokeName          = "smoke.dts";
};

SeekingMissileData MechPitViperMissilePack8Shot
{
   bulletShapeName = "pr_vip.dts";
   explosionTag    = MechImpMd;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 0.87;
   damageType      = $MissileDamageType;
   explosionRadius = 3.6;
   kickBackStrength = 250.0;
   muzzleVelocity   = 74.2;
   totalTime        = 2.67;
   liveTime         = 2.67;
   seekingTurningRadius    = 10.3;
   nonSeekingTurningRadius = 82.4;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

SeekingMissileData MechPitViperMissilePack12Shot
{
   bulletShapeName = "pr_vip.dts";
   explosionTag    = MechImpMd;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 0.87;
   damageType      = $MissileDamageType;
   explosionRadius = 3.6;
   kickBackStrength = 250.0;
   muzzleVelocity   = 74.2;
   totalTime        = 2.67;
   liveTime         = 2.67;
   seekingTurningRadius    = 10.3;
   nonSeekingTurningRadius = 82.4;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

SeekingMissileData MechSparrowMissilePack6Shot
{
   bulletShapeName = "pr_spr.dts";
   explosionTag    = MechImpMd;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 0.978;
   damageType      = $MissileDamageType;
   explosionRadius = 3.6;
   kickBackStrength = 250.0;
   muzzleVelocity   = 99.0;
   totalTime        = 2.5;
   liveTime         = 2.5;
   seekingTurningRadius    = 13.0;
   nonSeekingTurningRadius = 104.0;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

SeekingMissileData MechSparrowMissilePack10Shot
{
   bulletShapeName = "pr_spr.dts";
   explosionTag    = MechImpMd;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 0.978;
   damageType      = $MissileDamageType;
   explosionRadius = 3.6;
   kickBackStrength = 250.0;
   muzzleVelocity   = 99.0;
   totalTime        = 2.5;
   liveTime         = 2.5;
   seekingTurningRadius    = 13.0;
   nonSeekingTurningRadius = 104.0;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

SeekingMissileData MechSwarmMisslePack6Shot
{
   bulletShapeName = "pr_swrm.dts";
   explosionTag    = MechImpMd;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 1.196;
   damageType      = $MissileDamageType;
   explosionRadius = 3.6;
   kickBackStrength = 250.0;
   muzzleVelocity   = 111.4;
   totalTime        = 1.78;
   liveTime         = 1.78;
   seekingTurningRadius    = 15.5;
   nonSeekingTurningRadius = 124.0;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

SeekingMissileData MechMinionMisslePack10Shot
{
   bulletShapeName = "pr_min.dts";
   explosionTag    = MechImpMd;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 0.978;
   damageType      = $MissileDamageType;
   explosionRadius = 4.8;
   kickBackStrength = 250.0;
   muzzleVelocity   = 99.0;
   totalTime        = 3.0;
   liveTime         = 3.0;
   seekingTurningRadius    = 12.4;
   nonSeekingTurningRadius = 99.2;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

SeekingMissileData MechShrikeMisslePack8Shot
{
   bulletShapeName = "pr_shrk.dts";
   explosionTag    = MechImpMd;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 1.196;
   damageType      = $MissileDamageType;
   explosionRadius = 4.8;
   kickBackStrength = 250.0;
   muzzleVelocity   = 123.8;
   totalTime        = 1.5;
   liveTime         = 1.5;
   seekingTurningRadius    = 7.7;
   nonSeekingTurningRadius = 61.6;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

SeekingMissileData MechAphidAaMissileSystemPack10Shot
{
   bulletShapeName = "pr_min.dts";
   explosionTag    = MechImpMd;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 0.978;
   damageType      = $MissileDamageType;
   explosionRadius = 4.8;
   kickBackStrength = 250.0;
   muzzleVelocity   = 99.0;
   totalTime        = 7.5;
   liveTime         = 7.5;
   seekingTurningRadius    = 12.4;
   nonSeekingTurningRadius = 99.2;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

GrenadeData MechArachnitron4PackShot
{
   bulletShapeName    = "pr_ara.dts";
   explosionTag       = MechImpMd;
   collideWithOwner   = True;
   ownerGraceMS       = 600;
   collisionRadius    = 0.25;
   mass               = 6.0;
   elasticity         = 0.2;
   damageClass        = 1;
   damageValue        = 0.543;
   damageType         = $MineDamageType;
   explosionRadius    = 4.0;
   kickBackStrength   = 300.0;
   maxLevelFlightDist = 120;
   totalTime          = 30.0;
   liveTime           = 4.0;
   projSpecialTime    = 0.05;
   inheritedVelocityScale = 0.5;
   smokeName          = "smoke.dts";
};

GrenadeData MechArachnitron8PackShot
{
   bulletShapeName    = "pr_ara.dts";
   explosionTag       = MechImpMd;
   collideWithOwner   = True;
   ownerGraceMS       = 600;
   collisionRadius    = 0.25;
   mass               = 6.0;
   elasticity         = 0.2;
   damageClass        = 1;
   damageValue        = 0.543;
   damageType         = $MineDamageType;
   explosionRadius    = 4.0;
   kickBackStrength   = 300.0;
   maxLevelFlightDist = 120;
   totalTime          = 30.0;
   liveTime           = 4.0;
   projSpecialTime    = 0.05;
   inheritedVelocityScale = 0.5;
   smokeName          = "smoke.dts";
};

GrenadeData MechArachnitron12PackShot
{
   bulletShapeName    = "pr_ara.dts";
   explosionTag       = MechImpMd;
   collideWithOwner   = True;
   ownerGraceMS       = 600;
   collisionRadius    = 0.25;
   mass               = 6.0;
   elasticity         = 0.2;
   damageClass        = 1;
   damageValue        = 0.543;
   damageType         = $MineDamageType;
   explosionRadius    = 4.0;
   kickBackStrength   = 300.0;
   maxLevelFlightDist = 120;
   totalTime          = 30.0;
   liveTime           = 4.0;
   projSpecialTime    = 0.05;
   inheritedVelocityScale = 0.5;
   smokeName          = "smoke.dts";
};

GrenadeData MechProximity6PackShot
{
   bulletShapeName    = "pr_prx.dts";
   explosionTag       = MechImpMd;
   collideWithOwner   = True;
   ownerGraceMS       = 600;
   collisionRadius    = 0.25;
   mass               = 6.0;
   elasticity         = 0.2;
   damageClass        = 1;
   damageValue        = 0.761;
   damageType         = $MineDamageType;
   explosionRadius    = 9.0;
   kickBackStrength   = 300.0;
   maxLevelFlightDist = 120;
   totalTime          = 30.0;
   liveTime           = 4.0;
   projSpecialTime    = 0.05;
   inheritedVelocityScale = 0.5;
   smokeName          = "smoke.dts";
};

GrenadeData MechProximity10PackShot
{
   bulletShapeName    = "pr_prx.dts";
   explosionTag       = MechImpMd;
   collideWithOwner   = True;
   ownerGraceMS       = 600;
   collisionRadius    = 0.25;
   mass               = 6.0;
   elasticity         = 0.2;
   damageClass        = 1;
   damageValue        = 0.761;
   damageType         = $MineDamageType;
   explosionRadius    = 9.0;
   kickBackStrength   = 300.0;
   maxLevelFlightDist = 120;
   totalTime          = 30.0;
   liveTime           = 4.0;
   projSpecialTime    = 0.05;
   inheritedVelocityScale = 0.5;
   smokeName          = "smoke.dts";
};

GrenadeData MechProximity15PackShot
{
   bulletShapeName    = "pr_prx.dts";
   explosionTag       = MechImpMd;
   collideWithOwner   = True;
   ownerGraceMS       = 600;
   collisionRadius    = 0.25;
   mass               = 6.0;
   elasticity         = 0.2;
   damageClass        = 1;
   damageValue        = 0.761;
   damageType         = $MineDamageType;
   explosionRadius    = 9.0;
   kickBackStrength   = 300.0;
   maxLevelFlightDist = 120;
   totalTime          = 30.0;
   liveTime           = 4.0;
   projSpecialTime    = 0.05;
   inheritedVelocityScale = 0.5;
   smokeName          = "smoke.dts";
};

BulletData MechNikeSiegeGunShot
{
   bulletShapeName    = "pr_hbc.dts";
   explosionTag       = MechExpSm;
   damageClass        = 1;
   damageValue        = 1.63;
   damageType         = $ExplosionDamageType;
   explosionRadius    = 7.2;
   muzzleVelocity     = 135.0;
   totalTime          = 12.0;
   liveTime           = 8.4;
   lightRange         = 3.0;
   lightColor         = { 1.0, 0.8, 0.3 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

SeekingMissileData MechArtilleryMissleLauncherShot
{
   bulletShapeName = "pr_misl1.dts";
   explosionTag    = MechExpLg;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 1.63;
   damageType      = $MissileDamageType;
   explosionRadius = 7.2;
   kickBackStrength = 250.0;
   muzzleVelocity   = 123.8;
   totalTime        = 10.0;
   liveTime         = 10.0;
   seekingTurningRadius    = 17.2;
   nonSeekingTurningRadius = 137.6;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

LaserData MechRadiationGunShot
{
   laserBitmapName   = "fx_rad.bmp";
   hitName           = "fx_imp_tn.dts";
   damageConversion  = 0.0713;
   baseDamageType    = $ShrapnelDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 1.0, 0.4, 0.4 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

BulletData MechDisrupterShot
{
   bulletShapeName    = "pr_dis.dts";
   explosionTag       = MechImpTn;
   damageClass        = 0;
   damageValue        = 0.543;
   damageType         = $BlasterDamageType;
   muzzleVelocity     = 270.0;
   totalTime          = 1.25;
   liveTime           = 0.88;
   lightRange         = 3.0;
   lightColor         = { 0.25, 0.9, 1.0 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

LaserData MechSeismicProbeShot
{
   laserBitmapName   = "laserPulse.bmp";
   hitName           = "fx_exp_sm.dts";
   damageConversion  = 0.0715;
   baseDamageType    = $MortarDamageType;
   beamTime          = 0.35;
   lightRange        = 3.0;
   lightColor        = { 1.0, 0.4, 0.4 };
   detachFromShooter = true;
   hitSoundId        = SoundLaserHit;
};

BulletData MechArtilleryBatteryShot
{
   bulletShapeName    = "pr_hbc.dts";
   explosionTag       = MechExpSm;
   damageClass        = 1;
   damageValue        = 1.63;
   damageType         = $ExplosionDamageType;
   explosionRadius    = 7.2;
   muzzleVelocity     = 90.0;
   totalTime          = 12.0;
   liveTime           = 8.4;
   lightRange         = 3.0;
   lightColor         = { 1.0, 0.8, 0.3 };
   inheritedVelocityScale = 0.5;
   isVisible          = True;
   rotationPeriod     = 1;
};

SeekingMissileData MechScattergunShot
{
   bulletShapeName = "pr_hbc.dts";
   explosionTag    = MechImpMd;
   collisionRadius = 0.0;
   mass            = 2.0;
   damageClass     = 1;
   damageValue     = 0.217;
   damageType      = $MissileDamageType;
   explosionRadius = 2.0;
   kickBackStrength = 250.0;
   muzzleVelocity   = 49.5;
   totalTime        = 3.5;
   liveTime         = 3.5;
   seekingTurningRadius    = 4;
   nonSeekingTurningRadius = 32;
   proximityDist     = 2.5;
   smokeDist         = 1.75;
   lightRange       = 4.0;
   lightColor       = { 1.0, 0.75, 0.2 };
   inheritedVelocityScale = 0.5;
   soundId = SoundJetHeavy;
};

//--- weapon images + items --------------------------------------------------

ItemImageData MechLaserImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 1.03, 0.33 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.0;
   minEnergy  = 6.8;
   maxEnergy  = 5.3;
   projectileType = MechLaserShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechLaser
{
   heading = "bWeapons";
   description = "Laser [S]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechLaserImage;
   price = 435;
   showWeaponBar = true;
};

ItemImageData MechHeavyLaserImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 1.12, 0.27 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.3;
   minEnergy  = 11.3;
   maxEnergy  = 9.1;
   projectileType = MechHeavyLaserShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechHeavyLaser
{
   heading = "bWeapons";
   description = "Heavy Laser [M]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechHeavyLaserImage;
   price = 700;
   showWeaponBar = true;
};

ItemImageData MechCompressionLaserImage
{
   shapeFile  = "energygun";
   mountPoint = 1;
   fireOffset = { 0.0, 0.99, 0.36 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.5;
   minEnergy  = 5.0;
   maxEnergy  = 3.8;
   projectileType = MechCompressionLaserShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechCompressionLaser
{
   heading = "bWeapons";
   description = "Compression Laser [S]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechCompressionLaserImage;
   price = 570;
   showWeaponBar = true;
};

ItemImageData MechTwinLaserImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 0.85, 0.41 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.5;
   minEnergy  = 5.9;
   maxEnergy  = 4.6;
   projectileType = MechTwinLaserShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechTwinLaser
{
   heading = "bWeapons";
   description = "Twin Laser [S]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechTwinLaserImage;
   price = 495;
   showWeaponBar = true;
};

ItemImageData MechElectroMagneticPulseCannonImage
{
   shapeFile  = "energygun";
   mountPoint = 1;
   fireOffset = { 0.0, 0.99, 0.43 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.1;
   minEnergy  = 5.0;
   maxEnergy  = 3.8;
   projectileType = MechElectroMagneticPulseCannonShot;
   accuFire   = true;
   sfxFire    = SoundFireBlaster;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechElectroMagneticPulseCannon
{
   heading = "bWeapons";
   description = "Electro Magnetic Pulse Cannon [S]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "blaster";
   shadowDetailMask = 4;
   imageType = MechElectroMagneticPulseCannonImage;
   price = 610;
   showWeaponBar = true;
};

ItemImageData MechElectronFluxWhipImage
{
   shapeFile  = "energygun";
   mountPoint = 1;
   fireOffset = { 0.0, 0.45, 0.36 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.5;
   minEnergy  = 26.0;
   maxEnergy  = 21.3;
   projectileType = MechElectronFluxWhipShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechElectronFluxWhip
{
   heading = "bWeapons";
   description = "Electron Flux Whip [M]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechElectronFluxWhipImage;
   price = 820;
   showWeaponBar = true;
};

ItemImageData MechBlasterImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 0.99, 0.39 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.1;
   minEnergy  = 15.0;
   maxEnergy  = 12.2;
   projectileType = MechBlasterShot;
   accuFire   = true;
   sfxFire    = SoundFireBlaster;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechBlaster
{
   heading = "bWeapons";
   description = "Blaster [M]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "blaster";
   shadowDetailMask = 4;
   imageType = MechBlasterImage;
   price = 755;
   showWeaponBar = true;
};

ItemImageData MechHeavyBlasterImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 1.35, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.4;
   minEnergy  = 20.0;
   maxEnergy  = 16.3;
   projectileType = MechHeavyBlasterShot;
   accuFire   = true;
   sfxFire    = SoundFireBlaster;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechHeavyBlaster
{
   heading = "bWeapons";
   description = "Heavy Blaster [L]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "blaster";
   shadowDetailMask = 4;
   imageType = MechHeavyBlasterImage;
   price = 865;
   showWeaponBar = true;
};

ItemImageData MechParticleBeamWeaponImage
{
   shapeFile  = "energygun";
   mountPoint = 1;
   fireOffset = { 0.0, 0.45, 0.16 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.8;
   minEnergy  = 22.4;
   maxEnergy  = 18.3;
   projectileType = MechParticleBeamWeaponShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechParticleBeamWeapon
{
   heading = "bWeapons";
   description = "Particle Beam Weapon [L]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechParticleBeamWeaponImage;
   price = 900;
   showWeaponBar = true;
};

ItemImageData MechPlasmaImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 1.44, 0.47 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.9;
   minEnergy  = 15.0;
   maxEnergy  = 12.2;
   projectileType = MechPlasmaShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechPlasma
{
   heading = "bWeapons";
   description = "Plasma [L]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechPlasmaImage;
   price = 1025;
   showWeaponBar = true;
};

ItemImageData MechBlinkGunImage
{
   shapeFile  = "energygun";
   mountPoint = 1;
   fireOffset = { 0.0, 0.9, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 0.8;
   minEnergy  = 7.0;
   maxEnergy  = 5.5;
   projectileType = MechBlinkGunShot;
   accuFire   = true;
   sfxFire    = SoundFireBlaster;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechBlinkGun
{
   heading = "bWeapons";
   description = "Blink Gun [M]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "blaster";
   shadowDetailMask = 4;
   imageType = MechBlinkGunImage;
   price = 785;
   showWeaponBar = true;
};

ItemImageData MechQuantumGunImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 1.12, 0.54 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.0;
   minEnergy  = 29.6;
   maxEnergy  = 24.3;
   projectileType = MechQuantumGunShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechQuantumGun
{
   heading = "bWeapons";
   description = "Quantum Gun [X]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechQuantumGunImage;
   price = 1135;
   showWeaponBar = true;
};

ItemImageData MechMagnetoFusionAssaultCannonImage
{
   shapeFile  = "energygun";
   mountPoint = 1;
   fireOffset = { 0.0, 0.9, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.8;
   minEnergy  = 36.4;
   maxEnergy  = 30;
   projectileType = MechMagnetoFusionAssaultCannonShot;
   accuFire   = true;
   sfxFire    = SoundFireBlaster;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechMagnetoFusionAssaultCannon
{
   heading = "bWeapons";
   description = "Magneto-Fusion Assault Cannon [X]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "blaster";
   shadowDetailMask = 4;
   imageType = MechMagnetoFusionAssaultCannonImage;
   price = 1225;
   showWeaponBar = true;
};

ItemImageData MechNannoInfuserImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 0.68, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.7;
   minEnergy  = 13.2;
   maxEnergy  = 10.7;
   projectileType = MechNannoInfuserShot;
   accuFire   = true;
   sfxFire    = SoundFireBlaster;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechNannoInfuser
{
   heading = "bWeapons";
   description = "Nanno Infuser [S]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "blaster";
   shadowDetailMask = 4;
   imageType = MechNannoInfuserImage;
   price = 600;
   showWeaponBar = true;
};

ItemImageData MechNanniteCannonImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 1.24, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.7;
   minEnergy  = 18.6;
   maxEnergy  = 15.2;
   projectileType = MechNanniteCannonShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechNanniteCannon
{
   heading = "bWeapons";
   description = "Nannite Cannon [M]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechNanniteCannonImage;
   price = 660;
   showWeaponBar = true;
};

ItemImageData MechAutocannonImage
{
   shapeFile  = "chaingun";
   mountPoint = 1;
   fireOffset = { 0.0, 0.99, 0.32 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 0.5;
   minEnergy  = 5.9;
   maxEnergy  = 4.6;
   projectileType = MechAutocannonShot;
   accuFire   = true;
   sfxFire    = SoundFireChaingun;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechAutocannon
{
   heading = "bWeapons";
   description = "Autocannon [S]";
   className = "Weapon";
   shapeFile  = "chaingun";
   hudIcon = "chaingun";
   shadowDetailMask = 4;
   imageType = MechAutocannonImage;
   price = 400;
   showWeaponBar = true;
};

ItemImageData MechHeavyAutocannonImage
{
   shapeFile  = "chaingun";
   mountPoint = 1;
   fireOffset = { 0.0, 1.3, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 0.7;
   minEnergy  = 8.6;
   maxEnergy  = 6.8;
   projectileType = MechHeavyAutocannonShot;
   accuFire   = true;
   sfxFire    = SoundFireChaingun;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechHeavyAutocannon
{
   heading = "bWeapons";
   description = "Heavy Autocannon [M]";
   className = "Weapon";
   shapeFile  = "chaingun";
   hudIcon = "chaingun";
   shadowDetailMask = 4;
   imageType = MechHeavyAutocannonImage;
   price = 610;
   showWeaponBar = true;
};

ItemImageData MechElectroMagAutocannonImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 0.68, 0.23 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 0.6;
   minEnergy  = 6.8;
   maxEnergy  = 5.3;
   projectileType = MechElectroMagAutocannonShot;
   accuFire   = true;
   sfxFire    = SoundFireBlaster;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechElectroMagAutocannon
{
   heading = "bWeapons";
   description = "Electro-Mag Autocannon [S]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "blaster";
   shadowDetailMask = 4;
   imageType = MechElectroMagAutocannonImage;
   price = 520;
   showWeaponBar = true;
};

ItemImageData MechBlastCannonImage
{
   shapeFile  = "chaingun";
   mountPoint = 1;
   fireOffset = { 0.0, 1.35, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.7;
   minEnergy  = 11.3;
   maxEnergy  = 9.1;
   projectileType = MechBlastCannonShot;
   accuFire   = true;
   sfxFire    = SoundFireChaingun;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechBlastCannon
{
   heading = "bWeapons";
   description = "Blast Cannon [L]";
   className = "Weapon";
   shapeFile  = "chaingun";
   hudIcon = "chaingun";
   shadowDetailMask = 4;
   imageType = MechBlastCannonImage;
   price = 920;
   showWeaponBar = true;
};

ItemImageData MechHeavyBlastCannonImage
{
   shapeFile  = "chaingun";
   mountPoint = 0;
   fireOffset = { 0.0, 1.48, 0.52 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.0;
   minEnergy  = 15.0;
   maxEnergy  = 12.2;
   projectileType = MechHeavyBlastCannonShot;
   accuFire   = true;
   sfxFire    = SoundFireChaingun;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechHeavyBlastCannon
{
   heading = "bWeapons";
   description = "Heavy Blast Cannon [X]";
   className = "Weapon";
   shapeFile  = "chaingun";
   hudIcon = "chaingun";
   shadowDetailMask = 4;
   imageType = MechHeavyBlastCannonImage;
   price = 1015;
   showWeaponBar = true;
};

ItemImageData MechRailGunImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 1.44, 0.27 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.2;
   minEnergy  = 14.1;
   maxEnergy  = 11.4;
   projectileType = MechRailGunShot;
   accuFire   = true;
   sfxFire    = SoundFireBlaster;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechRailGun
{
   heading = "bWeapons";
   description = "Rail Gun [L]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "blaster";
   shadowDetailMask = 4;
   imageType = MechRailGunImage;
   price = 975;
   showWeaponBar = true;
};

ItemImageData MechLaserGuidedBombImage
{
   shapeFile  = "grenadeL";
   mountPoint = 0;
   fireOffset = { 0.0, 1.44, 0.27 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.0;
   minEnergy  = 22.4;
   maxEnergy  = 18.3;
   projectileType = MechLaserGuidedBombShot;
   accuFire   = true;
   sfxFire    = SoundFireGrenade;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechLaserGuidedBomb
{
   heading = "bWeapons";
   description = "Laser Guided Bomb [M]";
   className = "Weapon";
   shapeFile  = "grenadeL";
   hudIcon = "grenadelauncher";
   shadowDetailMask = 4;
   imageType = MechLaserGuidedBombImage;
   price = 500;
   showWeaponBar = true;
};

ItemImageData MechHadesImage
{
   shapeFile  = "grenadeL";
   mountPoint = 1;
   fireOffset = { 0.0, 1.44, 0.27 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.0;
   minEnergy  = 18.6;
   maxEnergy  = 15.2;
   projectileType = MechHadesShot;
   accuFire   = true;
   sfxFire    = SoundFireGrenade;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechHades
{
   heading = "bWeapons";
   description = "Hades [M]";
   className = "Weapon";
   shapeFile  = "grenadeL";
   hudIcon = "grenadelauncher";
   shadowDetailMask = 4;
   imageType = MechHadesImage;
   price = 500;
   showWeaponBar = true;
};

ItemImageData MechPitViperMissilePack8Image
{
   shapeFile  = "disc";
   mountPoint = 1;
   fireOffset = { 0.0, 0.9, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 3.0;
   minEnergy  = 15.0;
   maxEnergy  = 12.2;
   projectileType = MechPitViperMissilePack8Shot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechPitViperMissilePack8
{
   heading = "bWeapons";
   description = "Pit Viper Missile Pack 8 [S]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechPitViperMissilePack8Image;
   price = 605;
   showWeaponBar = true;
};

ItemImageData MechPitViperMissilePack12Image
{
   shapeFile  = "disc";
   mountPoint = 0;
   fireOffset = { 0.0, 0.9, 0.68 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 3.0;
   minEnergy  = 15.0;
   maxEnergy  = 12.2;
   projectileType = MechPitViperMissilePack12Shot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechPitViperMissilePack12
{
   heading = "bWeapons";
   description = "Pit Viper Missile Pack 12 [M]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechPitViperMissilePack12Image;
   price = 700;
   showWeaponBar = true;
};

ItemImageData MechSparrowMissilePack6Image
{
   shapeFile  = "disc";
   mountPoint = 0;
   fireOffset = { 0.0, 0.9, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.0;
   minEnergy  = 16.8;
   maxEnergy  = 13.7;
   projectileType = MechSparrowMissilePack6Shot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechSparrowMissilePack6
{
   heading = "bWeapons";
   description = "Sparrow Missile Pack 6 [S]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechSparrowMissilePack6Image;
   price = 490;
   showWeaponBar = true;
};

ItemImageData MechSparrowMissilePack10Image
{
   shapeFile  = "disc";
   mountPoint = 1;
   fireOffset = { 0.0, 0.9, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.0;
   minEnergy  = 16.8;
   maxEnergy  = 13.7;
   projectileType = MechSparrowMissilePack10Shot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechSparrowMissilePack10
{
   heading = "bWeapons";
   description = "Sparrow Missile Pack 10 [M]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechSparrowMissilePack10Image;
   price = 560;
   showWeaponBar = true;
};

ItemImageData MechSwarmMisslePack6Image
{
   shapeFile  = "disc";
   mountPoint = 0;
   fireOffset = { 0.0, 0.9, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.5;
   minEnergy  = 20.4;
   maxEnergy  = 16.7;
   projectileType = MechSwarmMisslePack6Shot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechSwarmMisslePack6
{
   heading = "bWeapons";
   description = "SWARM Missle Pack 6 [M]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechSwarmMisslePack6Image;
   price = 630;
   showWeaponBar = true;
};

ItemImageData MechMinionMisslePack10Image
{
   shapeFile  = "disc";
   mountPoint = 1;
   fireOffset = { 0.0, 0.9, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 4.0;
   minEnergy  = 16.8;
   maxEnergy  = 13.7;
   projectileType = MechMinionMisslePack10Shot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechMinionMisslePack10
{
   heading = "bWeapons";
   description = "Minion Missle Pack 10 [M]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechMinionMisslePack10Image;
   price = 840;
   showWeaponBar = true;
};

ItemImageData MechShrikeMisslePack8Image
{
   shapeFile  = "disc";
   mountPoint = 0;
   fireOffset = { 0.0, 0.9, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.0;
   minEnergy  = 20.4;
   maxEnergy  = 16.7;
   projectileType = MechShrikeMisslePack8Shot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechShrikeMisslePack8
{
   heading = "bWeapons";
   description = "Shrike Missle Pack 8 [M]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechShrikeMisslePack8Image;
   price = 800;
   showWeaponBar = true;
};

ItemImageData MechAphidAaMissileSystemPack10Image
{
   shapeFile  = "disc";
   mountPoint = 1;
   fireOffset = { 0.0, 0.9, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 3.0;
   minEnergy  = 16.8;
   maxEnergy  = 13.7;
   projectileType = MechAphidAaMissileSystemPack10Shot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechAphidAaMissileSystemPack10
{
   heading = "bWeapons";
   description = "Aphid AA Missile System Pack 10 [S]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechAphidAaMissileSystemPack10Image;
   price = 595;
   showWeaponBar = true;
};

ItemImageData MechArachnitron4PackImage
{
   shapeFile  = "grenadeL";
   mountPoint = 0;
   fireOffset = { 0.0, 0.45, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.0;
   minEnergy  = 9.5;
   maxEnergy  = 7.6;
   projectileType = MechArachnitron4PackShot;
   accuFire   = true;
   sfxFire    = SoundFireGrenade;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechArachnitron4Pack
{
   heading = "bWeapons";
   description = "Arachnitron 4 pack [S]";
   className = "Weapon";
   shapeFile  = "grenadeL";
   hudIcon = "grenadelauncher";
   shadowDetailMask = 4;
   imageType = MechArachnitron4PackImage;
   price = 410;
   showWeaponBar = true;
};

ItemImageData MechArachnitron8PackImage
{
   shapeFile  = "grenadeL";
   mountPoint = 1;
   fireOffset = { 0.0, 0.45, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.0;
   minEnergy  = 9.5;
   maxEnergy  = 7.6;
   projectileType = MechArachnitron8PackShot;
   accuFire   = true;
   sfxFire    = SoundFireGrenade;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechArachnitron8Pack
{
   heading = "bWeapons";
   description = "Arachnitron 8 pack [M]";
   className = "Weapon";
   shapeFile  = "grenadeL";
   hudIcon = "grenadelauncher";
   shadowDetailMask = 4;
   imageType = MechArachnitron8PackImage;
   price = 450;
   showWeaponBar = true;
};

ItemImageData MechArachnitron12PackImage
{
   shapeFile  = "grenadeL";
   mountPoint = 1;
   fireOffset = { 0.0, 0.45, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 2.0;
   minEnergy  = 9.5;
   maxEnergy  = 7.6;
   projectileType = MechArachnitron12PackShot;
   accuFire   = true;
   sfxFire    = SoundFireGrenade;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechArachnitron12Pack
{
   heading = "bWeapons";
   description = "Arachnitron 12 pack [L]";
   className = "Weapon";
   shapeFile  = "grenadeL";
   hudIcon = "grenadelauncher";
   shadowDetailMask = 4;
   imageType = MechArachnitron12PackImage;
   price = 490;
   showWeaponBar = true;
};

ItemImageData MechProximity6PackImage
{
   shapeFile  = "grenadeL";
   mountPoint = 1;
   fireOffset = { 0.0, 0.45, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.5;
   minEnergy  = 13.2;
   maxEnergy  = 10.7;
   projectileType = MechProximity6PackShot;
   accuFire   = true;
   sfxFire    = SoundFireGrenade;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechProximity6Pack
{
   heading = "bWeapons";
   description = "Proximity 6 pack [S]";
   className = "Weapon";
   shapeFile  = "grenadeL";
   hudIcon = "grenadelauncher";
   shadowDetailMask = 4;
   imageType = MechProximity6PackImage;
   price = 400;
   showWeaponBar = true;
};

ItemImageData MechProximity10PackImage
{
   shapeFile  = "grenadeL";
   mountPoint = 0;
   fireOffset = { 0.0, 0.45, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.5;
   minEnergy  = 13.2;
   maxEnergy  = 10.7;
   projectileType = MechProximity10PackShot;
   accuFire   = true;
   sfxFire    = SoundFireGrenade;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechProximity10Pack
{
   heading = "bWeapons";
   description = "Proximity 10 pack [M]";
   className = "Weapon";
   shapeFile  = "grenadeL";
   hudIcon = "grenadelauncher";
   shadowDetailMask = 4;
   imageType = MechProximity10PackImage;
   price = 425;
   showWeaponBar = true;
};

ItemImageData MechProximity15PackImage
{
   shapeFile  = "grenadeL";
   mountPoint = 0;
   fireOffset = { 0.0, 0.45, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.5;
   minEnergy  = 13.2;
   maxEnergy  = 10.7;
   projectileType = MechProximity15PackShot;
   accuFire   = true;
   sfxFire    = SoundFireGrenade;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechProximity15Pack
{
   heading = "bWeapons";
   description = "Proximity 15 pack [L]";
   className = "Weapon";
   shapeFile  = "grenadeL";
   hudIcon = "grenadelauncher";
   shadowDetailMask = 4;
   imageType = MechProximity15PackImage;
   price = 450;
   showWeaponBar = true;
};

ItemImageData MechNikeSiegeGunImage
{
   shapeFile  = "chaingun";
   mountPoint = 1;
   fireOffset = { 0.0, 5.96, 0.0 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 3.5;
   minEnergy  = 27.8;
   maxEnergy  = 22.8;
   projectileType = MechNikeSiegeGunShot;
   accuFire   = true;
   sfxFire    = SoundFireChaingun;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechNikeSiegeGun
{
   heading = "bWeapons";
   description = "Nike Siege Gun [X]";
   className = "Weapon";
   shapeFile  = "chaingun";
   hudIcon = "chaingun";
   shadowDetailMask = 4;
   imageType = MechNikeSiegeGunImage;
   price = 1000;
   showWeaponBar = true;
};

ItemImageData MechArtilleryMissleLauncherImage
{
   shapeFile  = "disc";
   mountPoint = 2;
   fireOffset = { 0.0, 0.09, 0.68 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 5.0;
   minEnergy  = 27.8;
   maxEnergy  = 22.8;
   projectileType = MechArtilleryMissleLauncherShot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechArtilleryMissleLauncher
{
   heading = "bWeapons";
   description = "Artillery Missle Launcher [X]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechArtilleryMissleLauncherImage;
   price = 1000;
   showWeaponBar = true;
};

ItemImageData MechRadiationGunImage
{
   shapeFile  = "energygun";
   mountPoint = 1;
   fireOffset = { 0.0, 0.68, 0.36 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.0;
   minEnergy  = 7.7;
   maxEnergy  = 6.1;
   projectileType = MechRadiationGunShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechRadiationGun
{
   heading = "bWeapons";
   description = "Radiation Gun [M]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechRadiationGunImage;
   price = 770;
   showWeaponBar = true;
};

ItemImageData MechDisrupterImage
{
   shapeFile  = "energygun";
   mountPoint = 0;
   fireOffset = { 0.0, 1.57, 0.45 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 1.0;
   minEnergy  = 9.5;
   maxEnergy  = 7.6;
   projectileType = MechDisrupterShot;
   accuFire   = true;
   sfxFire    = SoundFireBlaster;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechDisrupter
{
   heading = "bWeapons";
   description = "Disrupter [M]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "blaster";
   shadowDetailMask = 4;
   imageType = MechDisrupterImage;
   price = 600;
   showWeaponBar = true;
};

ItemImageData MechSeismicProbeImage
{
   shapeFile  = "energygun";
   mountPoint = 1;
   fireOffset = { 0.0, 0.09, 0.68 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 5.0;
   minEnergy  = 18.6;
   maxEnergy  = 15.2;
   projectileType = MechSeismicProbeShot;
   accuFire   = true;
   sfxFire    = SoundFireLaser;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechSeismicProbe
{
   heading = "bWeapons";
   description = "Seismic Probe [M]";
   className = "Weapon";
   shapeFile  = "energygun";
   hudIcon = "laserrifle";
   shadowDetailMask = 4;
   imageType = MechSeismicProbeImage;
   price = 1000;
   showWeaponBar = true;
};

ItemImageData MechArtilleryBatteryImage
{
   shapeFile  = "chaingun";
   mountPoint = 1;
   fireOffset = { 0.0, 7.04, 0.0 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 4.0;
   minEnergy  = 27.8;
   maxEnergy  = 22.8;
   projectileType = MechArtilleryBatteryShot;
   accuFire   = true;
   sfxFire    = SoundFireChaingun;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechArtilleryBattery
{
   heading = "bWeapons";
   description = "Artillery Battery [X]";
   className = "Weapon";
   shapeFile  = "chaingun";
   hudIcon = "chaingun";
   shadowDetailMask = 4;
   imageType = MechArtilleryBatteryImage;
   price = 1000;
   showWeaponBar = true;
};

ItemImageData MechScattergunImage
{
   shapeFile  = "disc";
   mountPoint = 0;
   fireOffset = { 0.0, 1.12, 0.32 };   // Starsiege weaponShot barrel offset
   weaponType = 0;
   reloadTime = 0;
   fireTime   = 0.8;
   minEnergy  = 4.0;
   maxEnergy  = 3.0;
   projectileType = MechScattergunShot;
   accuFire   = true;
   sfxFire    = SoundFireDisc;
   sfxActivate = SoundPickUpWeapon;
};

ItemData MechScattergun
{
   heading = "bWeapons";
   description = "Scattergun [M]";
   className = "Weapon";
   shapeFile  = "disc";
   hudIcon = "disclauncher";
   shadowDetailMask = 4;
   imageType = MechScattergunImage;
   price = 625;
   showWeaponBar = true;
};

//--- per-chassis authentic default loadouts --------------------------------
// One weapon per hardpoint, size-matched; roster rotates per chassis so the
// full arsenal shows up across the mech pool. grantLoadout (MechGame.cs)
// walks $MM::Loadout[chassis, i].

$MM::Loadout[HercCabasl, 0] = "MechProximity10Pack";
$MM::Loadout[HercCabasl, 1] = "MechArachnitron8Pack";
$MM::Loadout[HercCabasl, 2] = "MechNikeSiegeGun";
$MM::Loadout[HercCabasl, 3] = "MechArtilleryMissleLauncher";
$MM::LoadoutCount[HercCabasl] = 4;

$MM::Loadout[HercCinapoc, 0] = "MechArtilleryMissleLauncher";
$MM::Loadout[HercCinapoc, 1] = "MechArtilleryBattery";
$MM::Loadout[HercCinapoc, 2] = "MechArachnitron8Pack";
$MM::Loadout[HercCinapoc, 3] = "MechLaserGuidedBomb";
$MM::Loadout[HercCinapoc, 4] = "MechHades";
$MM::Loadout[HercCinapoc, 5] = "MechSparrowMissilePack10";
$MM::LoadoutCount[HercCinapoc] = 6;

$MM::Loadout[HercCinbasl, 0] = "MechArachnitron4Pack";
$MM::Loadout[HercCinbasl, 1] = "MechLaser";
$MM::Loadout[HercCinbasl, 2] = "MechArtilleryBattery";
$MM::Loadout[HercCinbasl, 3] = "MechHeavyBlastCannon";
$MM::LoadoutCount[HercCinbasl] = 4;

$MM::Loadout[HercCyexec, 0] = "MechHeavyBlastCannon";
$MM::Loadout[HercCyexec, 1] = "MechQuantumGun";
$MM::Loadout[HercCyexec, 2] = "MechParticleBeamWeapon";
$MM::Loadout[HercCyexec, 3] = "MechBlastCannon";
$MM::LoadoutCount[HercCyexec] = 4;

$MM::Loadout[HercCygoad, 0] = "MechSparrowMissilePack10";
$MM::Loadout[HercCygoad, 1] = "MechDisrupter";
$MM::LoadoutCount[HercCygoad] = 2;

$MM::Loadout[HercCyjudg, 0] = "MechDisrupter";
$MM::Loadout[HercCyjudg, 1] = "MechHeavyAutocannon";
$MM::Loadout[HercCyjudg, 2] = "MechMagnetoFusionAssaultCannon";
$MM::Loadout[HercCyjudg, 3] = "MechNikeSiegeGun";
$MM::LoadoutCount[HercCyjudg] = 4;

$MM::Loadout[HercCyprom, 0] = "MechNikeSiegeGun";
$MM::Loadout[HercCyprom, 1] = "MechArtilleryMissleLauncher";
$MM::Loadout[HercCyprom, 2] = "MechArtilleryBattery";
$MM::Loadout[HercCyprom, 3] = "MechHeavyBlastCannon";
$MM::Loadout[HercCyprom, 4] = "MechQuantumGun";
$MM::Loadout[HercCyprom, 5] = "MechMagnetoFusionAssaultCannon";
$MM::LoadoutCount[HercCyprom] = 6;

$MM::Loadout[HercCyseek, 0] = "MechScattergun";
$MM::Loadout[HercCyseek, 1] = "MechSwarmMisslePack6";
$MM::LoadoutCount[HercCyseek] = 2;

$MM::Loadout[HercCyshep, 0] = "MechSwarmMisslePack6";
$MM::Loadout[HercCyshep, 1] = "MechNanniteCannon";
$MM::Loadout[HercCyshep, 2] = "MechHeavyLaser";
$MM::Loadout[HercCyshep, 3] = "MechPitViperMissilePack12";
$MM::LoadoutCount[HercCyshep] = 4;

$MM::Loadout[HercHaapoc, 0] = "MechHeavyBlastCannon";
$MM::Loadout[HercHaapoc, 1] = "MechQuantumGun";
$MM::Loadout[HercHaapoc, 2] = "MechMagnetoFusionAssaultCannon";
$MM::Loadout[HercHaapoc, 3] = "MechNikeSiegeGun";
$MM::Loadout[HercHaapoc, 4] = "MechNannoInfuser";
$MM::Loadout[HercHaapoc, 5] = "MechPitViperMissilePack8";
$MM::LoadoutCount[HercHaapoc] = 6;

$MM::Loadout[HercKnapoc, 0] = "MechHeavyLaser";
$MM::Loadout[HercKnapoc, 1] = "MechPitViperMissilePack12";
$MM::Loadout[HercKnapoc, 2] = "MechQuantumGun";
$MM::Loadout[HercKnapoc, 3] = "MechMagnetoFusionAssaultCannon";
$MM::Loadout[HercKnapoc, 4] = "MechPitViperMissilePack8";
$MM::Loadout[HercKnapoc, 5] = "MechElectroMagneticPulseCannon";
$MM::LoadoutCount[HercKnapoc] = 6;

$MM::Loadout[HercKnbasl, 0] = "MechPitViperMissilePack12";
$MM::Loadout[HercKnbasl, 1] = "MechBlaster";
$MM::Loadout[HercKnbasl, 2] = "MechMagnetoFusionAssaultCannon";
$MM::Loadout[HercKnbasl, 3] = "MechNikeSiegeGun";
$MM::LoadoutCount[HercKnbasl] = 4;

$MM::Loadout[HercKngorg, 0] = "MechNikeSiegeGun";
$MM::Loadout[HercKngorg, 1] = "MechArtilleryMissleLauncher";
$MM::Loadout[HercKngorg, 2] = "MechRailGun";
$MM::Loadout[HercKngorg, 3] = "MechPlasma";
$MM::LoadoutCount[HercKngorg] = 4;

$MM::Loadout[HercKnmino, 0] = "MechProximity6Pack";
$MM::Loadout[HercKnmino, 1] = "MechArachnitron4Pack";
$MM::Loadout[HercKnmino, 2] = "MechRadiationGun";
$MM::Loadout[HercKnmino, 3] = "MechBlinkGun";
$MM::LoadoutCount[HercKnmino] = 4;

$MM::Loadout[HercKntalon, 0] = "MechBlinkGun";
$MM::Loadout[HercKntalon, 1] = "MechShrikeMisslePack8";
$MM::Loadout[HercKntalon, 2] = "MechProximity15Pack";
$MM::Loadout[HercKntalon, 3] = "MechArachnitron12Pack";
$MM::LoadoutCount[HercKntalon] = 4;

$MM::Loadout[HercMgexec, 0] = "MechHeavyBlastCannon";
$MM::Loadout[HercMgexec, 1] = "MechQuantumGun";
$MM::Loadout[HercMgexec, 2] = "MechArachnitron12Pack";
$MM::Loadout[HercMgexec, 3] = "MechHeavyBlaster";
$MM::LoadoutCount[HercMgexec] = 4;

$MM::Loadout[HercMggoad, 0] = "MechElectronFluxWhip";
$MM::Loadout[HercMggoad, 1] = "MechMinionMisslePack10";
$MM::LoadoutCount[HercMggoad] = 2;

$MM::Loadout[HercMgjudg, 0] = "MechMinionMisslePack10";
$MM::Loadout[HercMgjudg, 1] = "MechSeismicProbe";
$MM::Loadout[HercMgjudg, 2] = "MechMagnetoFusionAssaultCannon";
$MM::Loadout[HercMgjudg, 3] = "MechNikeSiegeGun";
$MM::LoadoutCount[HercMgjudg] = 4;

$MM::Loadout[HercMgseek, 0] = "MechSeismicProbe";
$MM::Loadout[HercMgseek, 1] = "MechProximity10Pack";
$MM::LoadoutCount[HercMgseek] = 2;

$MM::Loadout[HercMgshep, 0] = "MechProximity10Pack";
$MM::Loadout[HercMgshep, 1] = "MechArachnitron8Pack";
$MM::Loadout[HercMgshep, 2] = "MechLaserGuidedBomb";
$MM::Loadout[HercMgshep, 3] = "MechHades";
$MM::LoadoutCount[HercMgshep] = 4;

$MM::Loadout[HercPiapoc, 0] = "MechArachnitron8Pack";
$MM::Loadout[HercPiapoc, 1] = "MechLaserGuidedBomb";
$MM::Loadout[HercPiapoc, 2] = "MechArtilleryBattery";
$MM::Loadout[HercPiapoc, 3] = "MechHeavyBlastCannon";
$MM::Loadout[HercPiapoc, 4] = "MechAphidAaMissileSystemPack10";
$MM::Loadout[HercPiapoc, 5] = "MechNannoInfuser";
$MM::LoadoutCount[HercPiapoc] = 6;

$MM::Loadout[HercPieman, 0] = "MechHeavyBlastCannon";
$MM::Loadout[HercPieman, 1] = "MechLaserGuidedBomb";
$MM::LoadoutCount[HercPieman] = 2;

$MM::Loadout[HercPlexec, 0] = "MechQuantumGun";
$MM::Loadout[HercPlexec, 1] = "MechMagnetoFusionAssaultCannon";
$MM::Loadout[HercPlexec, 2] = "MechArachnitron12Pack";
$MM::Loadout[HercPlexec, 3] = "MechHeavyBlaster";
$MM::LoadoutCount[HercPlexec] = 4;

$MM::Loadout[HercPljudg, 0] = "MechSparrowMissilePack10";
$MM::Loadout[HercPljudg, 1] = "MechDisrupter";
$MM::Loadout[HercPljudg, 2] = "MechMagnetoFusionAssaultCannon";
$MM::Loadout[HercPljudg, 3] = "MechNikeSiegeGun";
$MM::LoadoutCount[HercPljudg] = 4;

$MM::Loadout[HercRbeman, 0] = "MechNikeSiegeGun";
$MM::Loadout[HercRbeman, 1] = "MechDisrupter";
$MM::LoadoutCount[HercRbeman] = 2;

$MM::Loadout[HercRboly, 0] = "MechArtilleryMissleLauncher";
$MM::Loadout[HercRboly, 1] = "MechArtilleryBattery";
$MM::Loadout[HercRboly, 2] = "MechBlastCannon";
$MM::Loadout[HercRboly, 3] = "MechRailGun";
$MM::Loadout[HercRboly, 4] = "MechProximity6Pack";
$MM::Loadout[HercRboly, 5] = "MechArachnitron4Pack";
$MM::LoadoutCount[HercRboly] = 6;

$MM::Loadout[HercTrapoc, 0] = "MechScattergun";
$MM::Loadout[HercTrapoc, 1] = "MechSwarmMisslePack6";
$MM::Loadout[HercTrapoc, 2] = "MechArtilleryBattery";
$MM::Loadout[HercTrapoc, 3] = "MechHeavyBlastCannon";
$MM::Loadout[HercTrapoc, 4] = "MechArachnitron4Pack";
$MM::Loadout[HercTrapoc, 5] = "MechLaser";
$MM::LoadoutCount[HercTrapoc] = 6;

$MM::Loadout[HercTrbasl, 0] = "MechSwarmMisslePack6";
$MM::Loadout[HercTrbasl, 1] = "MechNanniteCannon";
$MM::Loadout[HercTrbasl, 2] = "MechHeavyBlastCannon";
$MM::Loadout[HercTrbasl, 3] = "MechQuantumGun";
$MM::LoadoutCount[HercTrbasl] = 4;

$MM::Loadout[HercTrgorg, 0] = "MechQuantumGun";
$MM::Loadout[HercTrgorg, 1] = "MechMagnetoFusionAssaultCannon";
$MM::Loadout[HercTrgorg, 2] = "MechProximity15Pack";
$MM::Loadout[HercTrgorg, 3] = "MechArachnitron12Pack";
$MM::LoadoutCount[HercTrgorg] = 4;

$MM::Loadout[HercTrmino, 0] = "MechTwinLaser";
$MM::Loadout[HercTrmino, 1] = "MechElectroMagAutocannon";
$MM::Loadout[HercTrmino, 2] = "MechHeavyLaser";
$MM::Loadout[HercTrmino, 3] = "MechPitViperMissilePack12";
$MM::LoadoutCount[HercTrmino] = 4;

$MM::Loadout[HercTrtalon, 0] = "MechPitViperMissilePack12";
$MM::Loadout[HercTrtalon, 1] = "MechBlaster";
$MM::LoadoutCount[HercTrtalon] = 2;

echo("[MECH] MechWeapons: 44 authentic Starsiege weapons declared.");
