//----------------------------------------------------------------------------
// Mech Mayhem -- ESCALATION game mode (Stage 2).
// Bound by a mission's tail:  exec(MechGame);  $Game::missionType = "MechMay";
//
// Attrition TDM with Combat-Value tickets: each team starts with a shared CV
// pool; a death subtracts the fallen chassis' authentic Starsiege CV (Talon
// 1000 ... Executioner 3600). Pool empty -> the other team wins. Kills score
// via the normal DM plumbing too, so the scoreboard stays familiar.
//
// Builds on dm.cs (which execs game.cs); overrides below win the last-wins
// exec race. Heat tick + ticket refresh are kicked from Game::startMatch
// (survives the ConsoleScheduler recreation at mission load).
//----------------------------------------------------------------------------
exec(dm);
exec(MechHeat);
exec(MechDamage);
exec(MechWaves);
exec(MechZones);
exec(MechProgress);

$MM::TicketPool = 40000;

// Stage 2 roster: varied chassis, round-robin (garage picks come later).
$MechMayhem::ChassisCount = 6;
$MechMayhem::Chassis[0] = "HercKntalon";   // light
$MechMayhem::Chassis[1] = "HercCyseek";    // light
$MechMayhem::Chassis[2] = "HercKnmino";    // medium
$MechMayhem::Chassis[3] = "HercTrbasl";    // medium
$MechMayhem::Chassis[4] = "HercKnapoc";    // heavy
$MechMayhem::Chassis[5] = "HercKngorg";    // assault

function MechMayhem::pickChassis()
{
   %idx = $MechMayhem::NextChassis;
   if (%idx == "" || %idx < 0 || %idx >= $MechMayhem::ChassisCount)
      %idx = 0;
   $MechMayhem::NextChassis = %idx + 1;
   return $MechMayhem::Chassis[%idx];
}

// grant the default loadout for a chassis' hardpoint rack.
// The per-chassis tables ($MM::Loadout[chassis, i]) are GENERATED by
// tools/mech_weapon_gen.py from the authentic Starsiege hardpoint racks and
// the full mined arsenal -- one size-matched weapon per hardpoint, rotated
// across the roster so the whole arsenal appears across the mech pool.
function MechMayhem::grantLoadout(%pl, %clientId, %chassis)
{
   %n = $MM::LoadoutCount[%chassis];
   %first = "";
   if (%n != "" && %n > 0) {
      for (%i = 0; %i < %n; %i++) {
         %w = $MM::Loadout[%chassis, %i];
         if (%w != "") {
            Player::setItemCount(%clientId, %w, 1);
            if (%first == "") %first = %w;
         }
      }
   }
   if (%first == "") { Player::setItemCount(%clientId, MechLaser, 1); %first = MechLaser; }
   Player::setItemCount(%clientId, RepairKit, 1);
   Player::useItem(%pl, %first);
}

function Game::playerSpawned(%pl, %clientId, %armor)
{
   Client::setSkin(%clientId, $Client::info[%clientId, 0]);

   // a pilot's MMPick beats the round-robin; validity re-checked each spawn
   %chassis = %clientId.mmChassis;
   if (%chassis == "" || !MechProgress::canUse(%clientId, %chassis))
      %chassis = MechMayhem::pickChassis();
   Player::setArmor(%pl, %chassis);
   echo("[MECH] spawn: client " @ %clientId @ " -> " @ %chassis);

   MechShield::init(%pl, %chassis);
   MechMayhem::grantLoadout(%pl, %clientId, %chassis);

   if ($teamplay) {
      DMTEAM::checkMissionObjectives();
   }
}

//--- CV tickets --------------------------------------------------------------
// Player::onKilled fires for EVERY player death, humans and AI alike (the
// stock body handles %cl == -1). Chain: run the stock corpse logic first via
// a saved copy? No super in TribesScript -- so we re-implement the ticket
// accounting HERE and leave Player::onKilled itself alone; the hook below is
// GameBase-level: MechTickets::onDeath is called from MechHeat's tick when it
// sees a dead mech it hasn't accounted. Deaths are counted exactly once via
// the mmCounted flag on the corpse object.

function MechTickets::charge(%obj)
{
   if (%obj.mmCounted == 1)
      return;
   %obj.mmCounted = 1;
   %data = GameBase::getDataName(%obj);
   %base = MechHeat::baseChassis(%data);
   %cv = $MM::CV[%base];
   if (%cv == "")
      %cv = 1000;
   %team = GameBase::getTeam(%obj);
   if (%team < 0 || %team == "")
      return;
   if ($MM::Mode == "incursion") {
      // no ticket pools in PvE: Cybrid kills bank salvage (progression,
      // Stage 6); the wave director owns win/loss
      if (%team == 1) {
         $MMW::salvage = $MMW::salvage + %cv;
         echo("[MECHWAVE] salvage +" @ %cv @ " -> " @ $MMW::salvage);
      }
      return;
   }
   $MM::Tickets[%team] = $MM::Tickets[%team] - %cv;
   $teamScore[%team] = $MM::Tickets[%team];
   messageAll(0, Client::getName(Player::getClient(%obj)) @ "'s " @ %base
              @ " destroyed: team " @ getTeamName(%team) @ " loses " @ %cv
              @ " CV (" @ $MM::Tickets[%team] @ " left)");
   echo("[MECHCV] team " @ %team @ " -" @ %cv @ " -> " @ $MM::Tickets[%team]);
   if ($MM::Tickets[%team] <= 0)
      MechTickets::endMatch(%team);
}

// cockpit state channel: once a second per HUMAN-piloted mech, feed the
// mechcockpit ModernHUD pack (remoteMMState in its hud.cs). Bots skip it.
function MechHUD::push(%obj, %data)
{
   %cl = Player::getClient(%obj);
   if (%cl <= 0)
      return;
   %base = MechHeat::baseChassis(%data);
   %max = %base.maxEnergy;
   %heat = 0;
   if (%max > 0)
      %heat = 1 - (GameBase::getEnergy(%obj) / %max);
   %legs = 0;
   if (%obj.mmCrippled == 1) %legs = 2;
   %guns = 0;
   if (%obj.mmGunsLost > 0) %guns = 2;
   %sens = 0;
   if (%obj.mmSensorOut > getSimTime()) %sens = 2;
   %rctr = 0;
   if (%obj.mmReactorHit > getSimTime()) %rctr = 2;
   remoteEval(%cl, "MMState", %heat, %obj.mmShield, %obj.mmShieldMax,
              %legs, %guns, %sens, %rctr, %base, $MM::CV[%base],
              $MM::Tickets[0], $MM::Tickets[1], %obj.mmShutdown);
}

function MechTickets::visit(%obj)
{
   %data = GameBase::getDataName(%obj);
   if (String::getSubStr(%data, 0, 4) != "Herc")
      return;
   if (Player::isDead(%obj))
      MechTickets::charge(%obj);
   else
      MechHUD::push(%obj, %data);
}

function MechTickets::tick()
{
   Group::iterateRecursive(MissionCleanup, "MechTickets::visit");
   schedule("MechTickets::tick();", 1);
}

function MechTickets::endMatch(%loser)
{
   if ($MM::MatchOver == 1)
      return;
   $MM::MatchOver = 1;
   messageAll(0, "TEAM " @ getTeamName(%loser) @ " HAS BEEN ANNIHILATED.");
   $timeLimitReached = true;
   $timeReached = 1;
   DM::missionObjectives();
   schedule("Server::nextMission();", 12);
}

// stock game.cs:735 body + pilot record load
function Game::onPlayerConnected(%playerId)
{
   %playerId.scoreKills = 0;
   %playerId.scoreDeaths = 0;
   %playerId.score = 0;
   %playerId.justConnected = true;
   $menuMode[%playerId] = "None";
   Game::refreshClientScore(%playerId);
   MechProgress::load(%playerId);
}

// stock is an empty stub; save the pilot on the way out
function Client::leaveGame(%clientId)
{
   MechProgress::save(%clientId);
}

// dm.cs's version decrements $teamScore per kill, which fights the CV ticket
// pools; ours banks salvage for the killer instead. Non-team scoring (kills/
// deaths/obits) already happened in Client::onKilled before this dispatch.
function Game::clientKilled(%playerId, %killerId)
{
   if (%killerId != -1 && %playerId != -1 && %killerId != %playerId
       && (!$teamplay || Client::getTeam(%killerId) != Client::getTeam(%playerId))) {
      %victim = Client::getOwnedObject(%playerId);
      %chassis = "";
      if (%victim > 0)
         %chassis = MechHeat::baseChassis(GameBase::getDataName(%victim));
      MechProgress::creditKill(%killerId, %chassis);
   }
   if (%playerId != -1 && %playerId.mmKey != "")
      $MMP::deaths[%playerId.mmKey] = $MMP::deaths[%playerId.mmKey] + 1;
}

// Replaces the game.cs body (no super in TribesScript) -- the stock lines
// are replicated verbatim first, then the Mech Mayhem additions.
function Game::startMatch()
{
   // --- stock game.cs:373 body ---
   $matchStarted = true;
   $missionStartTime = getSimTime();
   messageAll(0, "Match started.");
   Game::resetScores();

   %numTeams = getNumTeams();
   for (%i = 0; %i < %numTeams; %i = %i + 1) {
      if ($TeamEnergy[%i] != "Infinite")
         schedule("replenishTeamEnergy(" @ %i @ ");", $secTeamEnergy);
   }

   for (%cl = Client::getFirst(); %cl != -1; %cl = Client::getNext(%cl))
   {
      if (%cl.observerMode == "pregame")
      {
         %cl.observerMode = "";
         Client::setControlObject(%cl, Client::getOwnedObject(%cl));
      }
      Game::refreshClientScore(%cl);
   }
   Game::checkTimeLimit();

   // --- Mech Mayhem ---
   $MM::MatchOver = 0;
   schedule("MechHeat::tick();", 2);
   schedule("MechTickets::tick();", 2);
   schedule("MechProgress::saveAll();", $MM::AutosaveSecs);
   if ($MM::Mode == "incursion") {
      MechWaves::start();
      echo("[MECH] INCURSION started.");
   }
   else {
      for (%i = 0; %i < %numTeams; %i++) {
         $MM::Tickets[%i] = $MM::TicketPool;
         $teamScore[%i] = $MM::TicketPool;
      }
      if ($MM::Mode == "groundwar") {
         MechZones::start();
         echo("[MECH] GROUNDWAR started: " @ $MM::ZoneCount @ " zones, " @ $MM::TicketPool @ " CV each.");
      }
      else
         echo("[MECH] ESCALATION started: " @ %numTeams @ " team(s), " @ $MM::TicketPool @ " CV each.");
   }
}

// INCURSION: every human defends -- no auto-balance onto the Cybrid team.
// Non-incursion path is the stock game.cs:745 body, verbatim.
function Game::assignClientTeam(%playerId)
{
   if ($MM::Mode == "incursion") {
      GameBase::setTeam(%playerId, 0);
      echo(Client::getName(%playerId), " assigned to the defense (incursion)");
      return;
   }
   if($teamplay)
   {
      %name = Client::getName(%playerId);
      %numTeams = getNumTeams();
      if($teamPreset[%name] != "")
      {
         if($teamPreset[%name] < %numTeams)
         {
            GameBase::setTeam(%playerId, $teamPreset[%name]);
            echo(Client::getName(%playerId), " was preset to team ", $teamPreset[%name]);
            return;
         }
      }
      %numPlayers = getNumClients();
      for(%i = 0; %i < %numTeams; %i = %i + 1)
         %numTeamPlayers[%i] = 0;

      for(%i = 0; %i < %numPlayers; %i = %i + 1)
      {
         %pl = getClientByIndex(%i);
         if(%pl != %playerId)
         {
            %team = Client::getTeam(%pl);
            %numTeamPlayers[%team] = %numTeamPlayers[%team] + 1;
         }
      }
      %leastPlayers = %numTeamPlayers[0];
      %leastTeam = 0;
      for(%i = 1; %i < %numTeams; %i = %i + 1)
      {
         if( (%numTeamPlayers[%i] < %leastPlayers) ||
            ( (%numTeamPlayers[%i] == %leastPlayers) &&
            ($teamScore[%i] < $teamScore[%leastTeam] ) ))
         {
            %leastTeam = %i;
            %leastPlayers = %numTeamPlayers;
         }
      }
      GameBase::setTeam(%playerId, %leastTeam);
      echo(Client::getName(%playerId), " was automatically assigned to team ", %leastTeam);
   }
   else
   {
      GameBase::setTeam(%playerId, 0);
   }
}
